### #9

Kaggle competition: [\[link\]](https://www.kaggle.com/competitions/playground-series-s5e9/)

Entry by Robin R.P.M. Kras

robkras.com

### ⭐ 1. Introduction & Overview

Your Goal: The goal of this competition is to predict a song's beats-per-minute.

### 🔹 2. Import Libraries & Set Up

In [37]:
# !/usr/bin/env python3
# -*- coding: utf-8 -*-

# =====================
# General utilities
# =====================
import json
import os
import pickle
import time
from collections import Counter

# =====================
# Data handling & processing
# =====================
import numpy as np
import pandas as pd
from tqdm import tqdm

# =====================
# Visualization
# =====================
import matplotlib.pyplot as plt
import seaborn as sns

# =====================
# Machine Learning - Core scikit-learn
# =====================
from sklearn.decomposition import PCA, TruncatedSVD
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.feature_selection import SelectKBest, chi2, mutual_info_classif
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, ElasticNet
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    mean_absolute_error, mean_squared_error, r2_score,
    root_mean_squared_error, roc_auc_score
)
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import LabelEncoder, StandardScaler, RobustScaler
from sklearn.svm import SVC, SVR

# =====================
# Machine Learning - Tree Boosting & advanced
# =====================
import xgboost as xg
import lightgbm as lgb
import catboost

# =====================
# Deep Learning - TensorFlow / Keras
# =====================
import tensorflow as tf
from keras import regularizers
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.layers import Dense, Dropout
from keras.models import Sequential
from keras.optimizers import Adam

# =====================
# Deep Learning - PyTorch
# =====================
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# import torch.optim as optim

# =====================
# Imbalanced data handling
# =====================
from imblearn.over_sampling import SMOTE

# =====================
# Optimization / AutoML
# =====================
import optuna

# =====================
# Feature importance & explainability
# =====================
import shap

# =====================
# Self Made Utilities
# =====================
from utils import *

# =====================
# Settings & reproducibility
# =====================
import warnings
warnings.filterwarnings("ignore")

SEED = 42
np.random.seed(SEED)

print("Libraries successfully loaded. Ready to go!")

Libraries successfully loaded. Ready to go!

In [38]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [39]:
train.head()

,id,RhythmScore,AudioLoudness,VocalContent,AcousticQuality,InstrumentalScore,LivePerformanceLikelihood,MoodScore,TrackDurationMs,Energy,BeatsPerMinute
0,0,0.603610,-7.636942,0.023500,0.000005,0.000001,0.051385,0.409866,290715.6450,0.826267,147.53020
1,1,0.639451,-16.267598,0.071520,0.444929,0.349414,0.170522,0.651010,164519.5174,0.145400,136.15963
2,2,0.514538,-15.953575,0.110715,0.173699,0.453814,0.029576,0.423865,174495.5667,0.624667,55.31989
3,3,0.734463,-1.357000,0.052965,0.001651,0.159717,0.086366,0.278745,225567.4651,0.487467,147.91212
4,4,0.532968,-13.056437,0.023500,0.068687,0.000001,0.331345,0.477769,213960.6789,0.947333,89.58511

In [ ]:
def create_features(df):
    df_new = df.copy()
    
    df_new['Rhythm_Energy'] = df_new['RhythmScore'] * df_new['Energy']
    df_new['Rhythm_Loudness'] = df_new['RhythmScore'] * df_new['AudioLoudness']
    
    df_new['Duration_Minutes'] = df_new['TrackDurationMs'] / 60000  # Convert to minutes
    df_new['Duration_Energy_Ratio'] = df_new['TrackDurationMs'] / (df_new['Energy'] * 10000 + 1) 
    
    df_new['RhythmScore_Squared'] = df_new['RhythmScore'] ** 2
    df_new['Energy_Squared'] = df_new['Energy'] ** 2
    df_new['Log_Duration'] = np.log1p(df_new['TrackDurationMs'])  # log(1+x) to handle zeros
    
    df_new['Acoustic_Instrumental_Ratio'] = df_new['AcousticQuality'] / (df_new['InstrumentalScore'] + 0.01) 
    df_new['Vocal_Energy'] = df_new['VocalContent'] * df_new['Energy']
    
    df_new['Live_Energy'] = df_new['LivePerformanceLikelihood'] * df_new['Energy']
    df_new['Mood_Rhythm'] = df_new['MoodScore'] * df_new['RhythmScore']
    
    df_new['Audio_Intensity'] = (df_new['Energy'] * np.abs(df_new['AudioLoudness'])) / 10 
    df_new['Performance_Character'] = (df_new['LivePerformanceLikelihood'] + df_new['MoodScore']) / 2
    
    df_new['Energy_Loudness_Ratio'] = df_new['Energy'] / (np.abs(df_new['AudioLoudness']) + 0.01)
    df_new['Rhythm_Duration_Density'] = df_new['RhythmScore'] / df_new['Duration_Minutes']

    # new below

    df_new['Log_RhythmScore'] = np.log1p(df_new['RhythmScore'])
    df_new['Log_Energy'] = np.log1p(df_new['Energy'])
    df_new['Log_AcousticQuality'] = np.log1p(df_new['AcousticQuality'])
    df_new['Log_InstrumentalScore'] = np.log1p(df_new['InstrumentalScore'])
    df_new['Log_VocalContent'] = np.log1p(df_new['VocalContent'])
    df_new['Log_LivePerformanceLikelihood'] = np.log1p(df_new['LivePerformanceLikelihood'])
    df_new['Log_MoodScore'] = np.log1p(df_new['MoodScore'])
    df_new['Log_AudioLoudness'] = np.log1p(np.abs(df_new['AudioLoudness']) + 1)
    
    return df_new

train = create_features(train)
test = create_features(test)

In [41]:
X = train.drop(["id", "BeatsPerMinute"], axis=1)
y = train["BeatsPerMinute"]

X_test = test.drop(["id"], axis=1)

In [42]:
for col in train.columns:
    if train[col].dtype == 'object':
        le = LabelEncoder()
        X[col] = le.fit_transform(X[col])
        X_test[col] = le.transform(X_test[col])

In [43]:
import lightgbm as lgb
from sklearn.model_selection import KFold

# Use 10-fold stratified cross-validation
n_splits = 10
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
y_probs_lgbm = np.zeros(len(X_test))
models = []

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    print(f"Training fold {fold + 1}/{n_splits} >>>")
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

    lightgbm = lgb.LGBMRegressor(
        n_estimators=20000,
        learning_rate=0.06,
        num_leaves=100,
        max_depth=10,
        min_child_samples=9,
        subsample=0.8,
        colsample_bytree=0.5,
        reg_alpha=0.78,
        reg_lambda=3.0,
        random_state=42,
        verbosity=-1,
        device="gpu",
        gpu_platform_id=0,
        gpu_device_id=0
    )
    
    lightgbm.fit(
        X_train, 
        y_train, 
        eval_set=[(X_val, y_val)], 
        callbacks=[
            lgb.early_stopping(100),
            lgb.log_evaluation(period=500)
        ]
    )

    models.append(lightgbm)
    
    # Average predictions across all folds
    y_probs_lgbm += lightgbm.predict(X_test) / n_splits

best_rmse = root_mean_squared_error(y, lightgbm.predict(X))
print(f"\nBest RMSE: {best_rmse:.4f}")

Training fold 1/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[23]	valid_0's l2: 698.886
Training fold 2/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[21]	valid_0's l2: 699.214
Training fold 3/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[27]	valid_0's l2: 703.021
Training fold 4/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[22]	valid_0's l2: 699.95
Training fold 5/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[35]	valid_0's l2: 703.343
Training fold 6/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 703.641
Training fold 7/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[28]	valid_0's l2: 699.463
Training fold 8/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[68]	valid_0's l2: 699.178
Training fold 9/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[21]	valid_0's l2: 696.984
Training fold 10/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[74]	valid_0's l2: 697.7

Best RMSE: 26.3049

In [44]:
import xgboost as xgb
from sklearn.model_selection import KFold

# Use 10-fold stratified cross-validation
n_splits = 10
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
y_probs_xgb = np.zeros(len(X_test))
models = []

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    print(f"Training fold {fold + 1}/{n_splits} >>>")
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

    xgboost = xgb.XGBRegressor(
        n_estimators=20000,
        learning_rate=0.06,
        max_depth=10,
        min_child_weight=9,
        subsample=0.8,
        colsample_bytree=0.5,
        reg_alpha=0.78,
        reg_lambda=3.0,
        random_state=42,
        early_stopping_rounds=100,
        verbosity=1,
        tree_method='gpu_hist',  # Use GPU acceleration
        gpu_id=0
    )
    
    xgboost.fit(
        X_train, 
        y_train, 
        eval_set=[(X_val, y_val)], 
    )

    models.append(xgboost)
    
    # Average predictions across all folds
    y_probs_xgb += xgboost.predict(X_test) / n_splits
    
best_rmse = root_mean_squared_error(y, xgboost.predict(X))
print(f"\nBest RMSE: {best_rmse:.4f}")

Training fold 1/10 >>>
[0]	validation_0-rmse:26.44166
[1]	validation_0-rmse:26.44167
[2]	validation_0-rmse:26.44131
[3]	validation_0-rmse:26.44147
[4]	validation_0-rmse:26.44224
[5]	validation_0-rmse:26.44249
[6]	validation_0-rmse:26.44291
[7]	validation_0-rmse:26.44329
[8]	validation_0-rmse:26.44303
[9]	validation_0-rmse:26.44140
[10]	validation_0-rmse:26.44264
[11]	validation_0-rmse:26.44296
[12]	validation_0-rmse:26.44258
[13]	validation_0-rmse:26.44246
[14]	validation_0-rmse:26.44200
[15]	validation_0-rmse:26.44282
[16]	validation_0-rmse:26.44407
[17]	validation_0-rmse:26.44279
[18]	validation_0-rmse:26.44316
[19]	validation_0-rmse:26.44479
[20]	validation_0-rmse:26.44477
[21]	validation_0-rmse:26.44529
[22]	validation_0-rmse:26.44550
[23]	validation_0-rmse:26.44599
[24]	validation_0-rmse:26.44670
[25]	validation_0-rmse:26.44755
[26]	validation_0-rmse:26.44844
[27]	validation_0-rmse:26.44804
[28]	validation_0-rmse:26.44813
[29]	validation_0-rmse:26.44765
[30]	validation_0-rmse:26.44723
[31]	validation_0-rmse:26.44661
[32]	validation_0-rmse:26.44754
[33]	validation_0-rmse:26.44818
[34]	validation_0-rmse:26.44902
[35]	validation_0-rmse:26.44884
[36]	validation_0-rmse:26.44932
[37]	validation_0-rmse:26.44945
[38]	validation_0-rmse:26.45042
[39]	validation_0-rmse:26.45149
[40]	validation_0-rmse:26.45171
[41]	validation_0-rmse:26.45201
[42]	validation_0-rmse:26.45224
[43]	validation_0-rmse:26.45330
[44]	validation_0-rmse:26.45323
[45]	validation_0-rmse:26.45357
[46]	validation_0-rmse:26.45468
[47]	validation_0-rmse:26.45440
[48]	validation_0-rmse:26.45510
[49]	validation_0-rmse:26.45498
[50]	validation_0-rmse:26.45550
[51]	validation_0-rmse:26.45598
[52]	validation_0-rmse:26.45621
[53]	validation_0-rmse:26.45587
[54]	validation_0-rmse:26.45657
[55]	validation_0-rmse:26.45617
[56]	validation_0-rmse:26.45662
[57]	validation_0-rmse:26.45596
[58]	validation_0-rmse:26.45695
[59]	validation_0-rmse:26.45652
[60]	validation_0-rmse:26.45669
[61]	validation_0-rmse:26.45670
[62]	validation_0-rmse:26.45758
[63]	validation_0-rmse:26.45770
[64]	validation_0-rmse:26.45776
[65]	validation_0-rmse:26.45852
[66]	validation_0-rmse:26.45900
[67]	validation_0-rmse:26.45958
[68]	validation_0-rmse:26.45942
[69]	validation_0-rmse:26.45971
[70]	validation_0-rmse:26.45924
[71]	validation_0-rmse:26.46023
[72]	validation_0-rmse:26.46040
[73]	validation_0-rmse:26.46059
[74]	validation_0-rmse:26.46121
[75]	validation_0-rmse:26.46191
[76]	validation_0-rmse:26.46186
[77]	validation_0-rmse:26.46189
[78]	validation_0-rmse:26.46243
[79]	validation_0-rmse:26.46299
[80]	validation_0-rmse:26.46347
[81]	validation_0-rmse:26.46402
[82]	validation_0-rmse:26.46432
[83]	validation_0-rmse:26.46330
[84]	validation_0-rmse:26.46315
[85]	validation_0-rmse:26.46347
[86]	validation_0-rmse:26.46371
[87]	validation_0-rmse:26.46375
[88]	validation_0-rmse:26.46408
[89]	validation_0-rmse:26.46397
[90]	validation_0-rmse:26.46403
[91]	validation_0-rmse:26.46384
[92]	validation_0-rmse:26.46383
[93]	validation_0-rmse:26.46414
[94]	validation_0-rmse:26.46426
[95]	validation_0-rmse:26.46468
[96]	validation_0-rmse:26.46513
[97]	validation_0-rmse:26.46556
[98]	validation_0-rmse:26.46616
[99]	validation_0-rmse:26.46629
[100]	validation_0-rmse:26.46717
[101]	validation_0-rmse:26.46804
Training fold 2/10 >>>
[0]	validation_0-rmse:26.44815
[1]	validation_0-rmse:26.44759
[2]	validation_0-rmse:26.44731
[3]	validation_0-rmse:26.44624
[4]	validation_0-rmse:26.44697
[5]	validation_0-rmse:26.44669
[6]	validation_0-rmse:26.44743
[7]	validation_0-rmse:26.44738
[8]	validation_0-rmse:26.44820
[9]	validation_0-rmse:26.44804
[10]	validation_0-rmse:26.44818
[11]	validation_0-rmse:26.44776
[12]	validation_0-rmse:26.44779
[13]	validation_0-rmse:26.44813
[14]	validation_0-rmse:26.44857
[15]	validation_0-rmse:26.44901
[16]	validation_0-rmse:26.44992
[17]	validation_0-rmse:26.45117
[18]	validation_0-rmse:26.45199
[19]	validation_0-rmse:26.45182
[20]	validation_0-rmse:26.45130
[21]	validation_0-rmse:26.45199
[22]	validation_0-rmse:26.45224
[23]	validation_0-rmse:26.45247
[24]	validation_0-rmse:26.45178
[25]	validation_0-rmse:26.45341
[26]	validation_0-rmse:26.45401
[27]	validation_0-rmse:26.45505
[28]	validation_0-rmse:26.45591
[29]	validation_0-rmse:26.45596
[30]	validation_0-rmse:26.45672
[31]	validation_0-rmse:26.45814
[32]	validation_0-rmse:26.45870
[33]	validation_0-rmse:26.45906
[34]	validation_0-rmse:26.46013
[35]	validation_0-rmse:26.46078
[36]	validation_0-rmse:26.46098
[37]	validation_0-rmse:26.46131
[38]	validation_0-rmse:26.46161
[39]	validation_0-rmse:26.46226
[40]	validation_0-rmse:26.46318
[41]	validation_0-rmse:26.46391
[42]	validation_0-rmse:26.46443
[43]	validation_0-rmse:26.46496
[44]	validation_0-rmse:26.46536
[45]	validation_0-rmse:26.46525
[46]	validation_0-rmse:26.46649
[47]	validation_0-rmse:26.46745
[48]	validation_0-rmse:26.46861
[49]	validation_0-rmse:26.46893
[50]	validation_0-rmse:26.46896
[51]	validation_0-rmse:26.46918
[52]	validation_0-rmse:26.46972
[53]	validation_0-rmse:26.47066
[54]	validation_0-rmse:26.46990
[55]	validation_0-rmse:26.46944
[56]	validation_0-rmse:26.47007
[57]	validation_0-rmse:26.47068
[58]	validation_0-rmse:26.47155
[59]	validation_0-rmse:26.47242
[60]	validation_0-rmse:26.47284
[61]	validation_0-rmse:26.47408
[62]	validation_0-rmse:26.47389
[63]	validation_0-rmse:26.47371
[64]	validation_0-rmse:26.47438
[65]	validation_0-rmse:26.47477
[66]	validation_0-rmse:26.47534
[67]	validation_0-rmse:26.47633
[68]	validation_0-rmse:26.47738
[69]	validation_0-rmse:26.47825
[70]	validation_0-rmse:26.47838
[71]	validation_0-rmse:26.47868
[72]	validation_0-rmse:26.47867
[73]	validation_0-rmse:26.47817
[74]	validation_0-rmse:26.47744
[75]	validation_0-rmse:26.47892
[76]	validation_0-rmse:26.47891
[77]	validation_0-rmse:26.47992
[78]	validation_0-rmse:26.47995
[79]	validation_0-rmse:26.48082
[80]	validation_0-rmse:26.48013
[81]	validation_0-rmse:26.48053
[82]	validation_0-rmse:26.48155
[83]	validation_0-rmse:26.48279
[84]	validation_0-rmse:26.48355
[85]	validation_0-rmse:26.48431
[86]	validation_0-rmse:26.48432
[87]	validation_0-rmse:26.48401
[88]	validation_0-rmse:26.48424
[89]	validation_0-rmse:26.48472
[90]	validation_0-rmse:26.48545
[91]	validation_0-rmse:26.48589
[92]	validation_0-rmse:26.48592
[93]	validation_0-rmse:26.48598
[94]	validation_0-rmse:26.48693
[95]	validation_0-rmse:26.48795
[96]	validation_0-rmse:26.48919
[97]	validation_0-rmse:26.48837
[98]	validation_0-rmse:26.48888
[99]	validation_0-rmse:26.48876
[100]	validation_0-rmse:26.49014
[101]	validation_0-rmse:26.49037
[102]	validation_0-rmse:26.49128
[103]	validation_0-rmse:26.49259
Training fold 3/10 >>>
[0]	validation_0-rmse:26.52338
[1]	validation_0-rmse:26.52409
[2]	validation_0-rmse:26.52309
[3]	validation_0-rmse:26.52152
[4]	validation_0-rmse:26.52161
[5]	validation_0-rmse:26.52126
[6]	validation_0-rmse:26.52066
[7]	validation_0-rmse:26.52061
[8]	validation_0-rmse:26.52027
[9]	validation_0-rmse:26.52041
[10]	validation_0-rmse:26.52093
[11]	validation_0-rmse:26.52103
[12]	validation_0-rmse:26.52068
[13]	validation_0-rmse:26.51981
[14]	validation_0-rmse:26.51936
[15]	validation_0-rmse:26.51845
[16]	validation_0-rmse:26.51801
[17]	validation_0-rmse:26.51847
[18]	validation_0-rmse:26.51891
[19]	validation_0-rmse:26.51918
[20]	validation_0-rmse:26.51882
[21]	validation_0-rmse:26.51892
[22]	validation_0-rmse:26.51923
[23]	validation_0-rmse:26.51954
[24]	validation_0-rmse:26.51987
[25]	validation_0-rmse:26.51983
[26]	validation_0-rmse:26.51966
[27]	validation_0-rmse:26.51973
[28]	validation_0-rmse:26.52060
[29]	validation_0-rmse:26.52158
[30]	validation_0-rmse:26.52166
[31]	validation_0-rmse:26.52115
[32]	validation_0-rmse:26.52096
[33]	validation_0-rmse:26.52123
[34]	validation_0-rmse:26.52114
[35]	validation_0-rmse:26.52072
[36]	validation_0-rmse:26.52041
[37]	validation_0-rmse:26.52054
[38]	validation_0-rmse:26.52189
[39]	validation_0-rmse:26.52257
[40]	validation_0-rmse:26.52317
[41]	validation_0-rmse:26.52393
[42]	validation_0-rmse:26.52373
[43]	validation_0-rmse:26.52503
[44]	validation_0-rmse:26.52517
[45]	validation_0-rmse:26.52505
[46]	validation_0-rmse:26.52512
[47]	validation_0-rmse:26.52643
[48]	validation_0-rmse:26.52725
[49]	validation_0-rmse:26.52650
[50]	validation_0-rmse:26.52745
[51]	validation_0-rmse:26.52705
[52]	validation_0-rmse:26.52704
[53]	validation_0-rmse:26.52705
[54]	validation_0-rmse:26.52801
[55]	validation_0-rmse:26.52849
[56]	validation_0-rmse:26.52921
[57]	validation_0-rmse:26.52901
[58]	validation_0-rmse:26.52957
[59]	validation_0-rmse:26.53024
[60]	validation_0-rmse:26.53064
[61]	validation_0-rmse:26.53049
[62]	validation_0-rmse:26.53033
[63]	validation_0-rmse:26.53078
[64]	validation_0-rmse:26.53108
[65]	validation_0-rmse:26.53094
[66]	validation_0-rmse:26.53147
[67]	validation_0-rmse:26.53289
[68]	validation_0-rmse:26.53269
[69]	validation_0-rmse:26.53242
[70]	validation_0-rmse:26.53244
[71]	validation_0-rmse:26.53288
[72]	validation_0-rmse:26.53265
[73]	validation_0-rmse:26.53325
[74]	validation_0-rmse:26.53449
[75]	validation_0-rmse:26.53494
[76]	validation_0-rmse:26.53516
[77]	validation_0-rmse:26.53646
[78]	validation_0-rmse:26.53683
[79]	validation_0-rmse:26.53683
[80]	validation_0-rmse:26.53758
[81]	validation_0-rmse:26.53840
[82]	validation_0-rmse:26.53905
[83]	validation_0-rmse:26.53901
[84]	validation_0-rmse:26.53901
[85]	validation_0-rmse:26.53939
[86]	validation_0-rmse:26.53965
[87]	validation_0-rmse:26.53986
[88]	validation_0-rmse:26.53978
[89]	validation_0-rmse:26.54073
[90]	validation_0-rmse:26.54205
[91]	validation_0-rmse:26.54205
[92]	validation_0-rmse:26.54164
[93]	validation_0-rmse:26.54221
[94]	validation_0-rmse:26.54262
[95]	validation_0-rmse:26.54230
[96]	validation_0-rmse:26.54312
[97]	validation_0-rmse:26.54358
[98]	validation_0-rmse:26.54398
[99]	validation_0-rmse:26.54434
[100]	validation_0-rmse:26.54576
[101]	validation_0-rmse:26.54615
[102]	validation_0-rmse:26.54616
[103]	validation_0-rmse:26.54795
[104]	validation_0-rmse:26.54881
[105]	validation_0-rmse:26.54958
[106]	validation_0-rmse:26.54972
[107]	validation_0-rmse:26.55077
[108]	validation_0-rmse:26.55170
[109]	validation_0-rmse:26.55229
[110]	validation_0-rmse:26.55326
[111]	validation_0-rmse:26.55366
[112]	validation_0-rmse:26.55388
[113]	validation_0-rmse:26.55370
[114]	validation_0-rmse:26.55375
[115]	validation_0-rmse:26.55411
Training fold 4/10 >>>
[0]	validation_0-rmse:26.46226
[1]	validation_0-rmse:26.46225
[2]	validation_0-rmse:26.46199
[3]	validation_0-rmse:26.46164
[4]	validation_0-rmse:26.46089
[5]	validation_0-rmse:26.45914
[6]	validation_0-rmse:26.45922
[7]	validation_0-rmse:26.45966
[8]	validation_0-rmse:26.45927
[9]	validation_0-rmse:26.45915
[10]	validation_0-rmse:26.45895
[11]	validation_0-rmse:26.45931
[12]	validation_0-rmse:26.45991
[13]	validation_0-rmse:26.46020
[14]	validation_0-rmse:26.46092
[15]	validation_0-rmse:26.46154
[16]	validation_0-rmse:26.46201
[17]	validation_0-rmse:26.46201
[18]	validation_0-rmse:26.46174
[19]	validation_0-rmse:26.46265
[20]	validation_0-rmse:26.46271
[21]	validation_0-rmse:26.46280
[22]	validation_0-rmse:26.46398
[23]	validation_0-rmse:26.46323
[24]	validation_0-rmse:26.46325
[25]	validation_0-rmse:26.46376
[26]	validation_0-rmse:26.46367
[27]	validation_0-rmse:26.46482
[28]	validation_0-rmse:26.46425
[29]	validation_0-rmse:26.46430
[30]	validation_0-rmse:26.46554
[31]	validation_0-rmse:26.46598
[32]	validation_0-rmse:26.46674
[33]	validation_0-rmse:26.46727
[34]	validation_0-rmse:26.46749
[35]	validation_0-rmse:26.46726
[36]	validation_0-rmse:26.46735
[37]	validation_0-rmse:26.46783
[38]	validation_0-rmse:26.46908
[39]	validation_0-rmse:26.47063
[40]	validation_0-rmse:26.47008
[41]	validation_0-rmse:26.47003
[42]	validation_0-rmse:26.47027
[43]	validation_0-rmse:26.47082
[44]	validation_0-rmse:26.47104
[45]	validation_0-rmse:26.47076
[46]	validation_0-rmse:26.47117
[47]	validation_0-rmse:26.47222
[48]	validation_0-rmse:26.47236
[49]	validation_0-rmse:26.47359
[50]	validation_0-rmse:26.47325
[51]	validation_0-rmse:26.47324
[52]	validation_0-rmse:26.47371
[53]	validation_0-rmse:26.47444
[54]	validation_0-rmse:26.47591
[55]	validation_0-rmse:26.47596
[56]	validation_0-rmse:26.47529
[57]	validation_0-rmse:26.47603
[58]	validation_0-rmse:26.47650
[59]	validation_0-rmse:26.47633
[60]	validation_0-rmse:26.47785
[61]	validation_0-rmse:26.47869
[62]	validation_0-rmse:26.47898
[63]	validation_0-rmse:26.47805
[64]	validation_0-rmse:26.47884
[65]	validation_0-rmse:26.47895
[66]	validation_0-rmse:26.47937
[67]	validation_0-rmse:26.48044
[68]	validation_0-rmse:26.48073
[69]	validation_0-rmse:26.48164
[70]	validation_0-rmse:26.48260
[71]	validation_0-rmse:26.48402
[72]	validation_0-rmse:26.48463
[73]	validation_0-rmse:26.48536
[74]	validation_0-rmse:26.48558
[75]	validation_0-rmse:26.48637
[76]	validation_0-rmse:26.48606
[77]	validation_0-rmse:26.48674
[78]	validation_0-rmse:26.48664
[79]	validation_0-rmse:26.48728
[80]	validation_0-rmse:26.48779
[81]	validation_0-rmse:26.48813
[82]	validation_0-rmse:26.48914
[83]	validation_0-rmse:26.48958
[84]	validation_0-rmse:26.49009
[85]	validation_0-rmse:26.49039
[86]	validation_0-rmse:26.49028
[87]	validation_0-rmse:26.49055
[88]	validation_0-rmse:26.49146
[89]	validation_0-rmse:26.49201
[90]	validation_0-rmse:26.49237
[91]	validation_0-rmse:26.49257
[92]	validation_0-rmse:26.49268
[93]	validation_0-rmse:26.49279
[94]	validation_0-rmse:26.49304
[95]	validation_0-rmse:26.49281
[96]	validation_0-rmse:26.49323
[97]	validation_0-rmse:26.49406
[98]	validation_0-rmse:26.49474
[99]	validation_0-rmse:26.49639
[100]	validation_0-rmse:26.49720
[101]	validation_0-rmse:26.49741
[102]	validation_0-rmse:26.49791
[103]	validation_0-rmse:26.49914
[104]	validation_0-rmse:26.49927
[105]	validation_0-rmse:26.50063
[106]	validation_0-rmse:26.50059
[107]	validation_0-rmse:26.50136
[108]	validation_0-rmse:26.50177
[109]	validation_0-rmse:26.50249
Training fold 5/10 >>>
[0]	validation_0-rmse:26.53009
[1]	validation_0-rmse:26.52919
[2]	validation_0-rmse:26.52930
[3]	validation_0-rmse:26.52848
[4]	validation_0-rmse:26.52838
[5]	validation_0-rmse:26.52765
[6]	validation_0-rmse:26.52884
[7]	validation_0-rmse:26.52817
[8]	validation_0-rmse:26.52792
[9]	validation_0-rmse:26.52801
[10]	validation_0-rmse:26.52845
[11]	validation_0-rmse:26.52884
[12]	validation_0-rmse:26.53070
[13]	validation_0-rmse:26.53120
[14]	validation_0-rmse:26.53096
[15]	validation_0-rmse:26.53126
[16]	validation_0-rmse:26.53206
[17]	validation_0-rmse:26.53270
[18]	validation_0-rmse:26.53271
[19]	validation_0-rmse:26.53223
[20]	validation_0-rmse:26.53319
[21]	validation_0-rmse:26.53206
[22]	validation_0-rmse:26.53220
[23]	validation_0-rmse:26.53247
[24]	validation_0-rmse:26.53294
[25]	validation_0-rmse:26.53291
[26]	validation_0-rmse:26.53401
[27]	validation_0-rmse:26.53549
[28]	validation_0-rmse:26.53542
[29]	validation_0-rmse:26.53580
[30]	validation_0-rmse:26.53609
[31]	validation_0-rmse:26.53646
[32]	validation_0-rmse:26.53705
[33]	validation_0-rmse:26.53646
[34]	validation_0-rmse:26.53701
[35]	validation_0-rmse:26.53877
[36]	validation_0-rmse:26.53911
[37]	validation_0-rmse:26.54005
[38]	validation_0-rmse:26.54044
[39]	validation_0-rmse:26.54058
[40]	validation_0-rmse:26.54118
[41]	validation_0-rmse:26.54196
[42]	validation_0-rmse:26.54215
[43]	validation_0-rmse:26.54137
[44]	validation_0-rmse:26.54141
[45]	validation_0-rmse:26.54118
[46]	validation_0-rmse:26.54095
[47]	validation_0-rmse:26.54174
[48]	validation_0-rmse:26.54263
[49]	validation_0-rmse:26.54290
[50]	validation_0-rmse:26.54295
[51]	validation_0-rmse:26.54386
[52]	validation_0-rmse:26.54374
[53]	validation_0-rmse:26.54347
[54]	validation_0-rmse:26.54354
[55]	validation_0-rmse:26.54319
[56]	validation_0-rmse:26.54370
[57]	validation_0-rmse:26.54392
[58]	validation_0-rmse:26.54404
[59]	validation_0-rmse:26.54375
[60]	validation_0-rmse:26.54343
[61]	validation_0-rmse:26.54387
[62]	validation_0-rmse:26.54346
[63]	validation_0-rmse:26.54345
[64]	validation_0-rmse:26.54370
[65]	validation_0-rmse:26.54470
[66]	validation_0-rmse:26.54478
[67]	validation_0-rmse:26.54523
[68]	validation_0-rmse:26.54496
[69]	validation_0-rmse:26.54554
[70]	validation_0-rmse:26.54515
[71]	validation_0-rmse:26.54437
[72]	validation_0-rmse:26.54541
[73]	validation_0-rmse:26.54557
[74]	validation_0-rmse:26.54573
[75]	validation_0-rmse:26.54623
[76]	validation_0-rmse:26.54673
[77]	validation_0-rmse:26.54691
[78]	validation_0-rmse:26.54735
[79]	validation_0-rmse:26.54839
[80]	validation_0-rmse:26.54880
[81]	validation_0-rmse:26.54950
[82]	validation_0-rmse:26.54982
[83]	validation_0-rmse:26.54939
[84]	validation_0-rmse:26.54966
[85]	validation_0-rmse:26.55006
[86]	validation_0-rmse:26.55025
[87]	validation_0-rmse:26.54994
[88]	validation_0-rmse:26.55140
[89]	validation_0-rmse:26.55215
[90]	validation_0-rmse:26.55263
[91]	validation_0-rmse:26.55319
[92]	validation_0-rmse:26.55391
[93]	validation_0-rmse:26.55420
[94]	validation_0-rmse:26.55449
[95]	validation_0-rmse:26.55453
[96]	validation_0-rmse:26.55493
[97]	validation_0-rmse:26.55486
[98]	validation_0-rmse:26.55543
[99]	validation_0-rmse:26.55610
[100]	validation_0-rmse:26.55708
[101]	validation_0-rmse:26.55731
[102]	validation_0-rmse:26.55818
[103]	validation_0-rmse:26.55950
[104]	validation_0-rmse:26.56017
[105]	validation_0-rmse:26.56027
Training fold 6/10 >>>
[0]	validation_0-rmse:26.53261
[1]	validation_0-rmse:26.53220
[2]	validation_0-rmse:26.53054
[3]	validation_0-rmse:26.53120
[4]	validation_0-rmse:26.53094
[5]	validation_0-rmse:26.53163
[6]	validation_0-rmse:26.53157
[7]	validation_0-rmse:26.53229
[8]	validation_0-rmse:26.53198
[9]	validation_0-rmse:26.53187
[10]	validation_0-rmse:26.53215
[11]	validation_0-rmse:26.53178
[12]	validation_0-rmse:26.53174
[13]	validation_0-rmse:26.53164
[14]	validation_0-rmse:26.53239
[15]	validation_0-rmse:26.53208
[16]	validation_0-rmse:26.53284
[17]	validation_0-rmse:26.53288
[18]	validation_0-rmse:26.53237
[19]	validation_0-rmse:26.53251
[20]	validation_0-rmse:26.53260
[21]	validation_0-rmse:26.53332
[22]	validation_0-rmse:26.53410
[23]	validation_0-rmse:26.53571
[24]	validation_0-rmse:26.53603
[25]	validation_0-rmse:26.53717
[26]	validation_0-rmse:26.53870
[27]	validation_0-rmse:26.53857
[28]	validation_0-rmse:26.53898
[29]	validation_0-rmse:26.53916
[30]	validation_0-rmse:26.53880
[31]	validation_0-rmse:26.53884
[32]	validation_0-rmse:26.53858
[33]	validation_0-rmse:26.53901
[34]	validation_0-rmse:26.53963
[35]	validation_0-rmse:26.53968
[36]	validation_0-rmse:26.53915
[37]	validation_0-rmse:26.53978
[38]	validation_0-rmse:26.53939
[39]	validation_0-rmse:26.54043
[40]	validation_0-rmse:26.54120
[41]	validation_0-rmse:26.54188
[42]	validation_0-rmse:26.54285
[43]	validation_0-rmse:26.54227
[44]	validation_0-rmse:26.54224
[45]	validation_0-rmse:26.54381
[46]	validation_0-rmse:26.54467
[47]	validation_0-rmse:26.54473
[48]	validation_0-rmse:26.54522
[49]	validation_0-rmse:26.54496
[50]	validation_0-rmse:26.54538
[51]	validation_0-rmse:26.54598
[52]	validation_0-rmse:26.54632
[53]	validation_0-rmse:26.54653
[54]	validation_0-rmse:26.54594
[55]	validation_0-rmse:26.54622
[56]	validation_0-rmse:26.54731
[57]	validation_0-rmse:26.54777
[58]	validation_0-rmse:26.54807
[59]	validation_0-rmse:26.54843
[60]	validation_0-rmse:26.54825
[61]	validation_0-rmse:26.54906
[62]	validation_0-rmse:26.54850
[63]	validation_0-rmse:26.54753
[64]	validation_0-rmse:26.54732
[65]	validation_0-rmse:26.54791
[66]	validation_0-rmse:26.54914
[67]	validation_0-rmse:26.54892
[68]	validation_0-rmse:26.55000
[69]	validation_0-rmse:26.55045
[70]	validation_0-rmse:26.55097
[71]	validation_0-rmse:26.55096
[72]	validation_0-rmse:26.55069
[73]	validation_0-rmse:26.55085
[74]	validation_0-rmse:26.55111
[75]	validation_0-rmse:26.55150
[76]	validation_0-rmse:26.55193
[77]	validation_0-rmse:26.55280
[78]	validation_0-rmse:26.55229
[79]	validation_0-rmse:26.55283
[80]	validation_0-rmse:26.55279
[81]	validation_0-rmse:26.55331
[82]	validation_0-rmse:26.55366

Best RMSE: 26.4178

In [45]:
import catboost as cb
from sklearn.model_selection import KFold

# Use 10-fold stratified cross-validation
n_splits = 10
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
y_probs_cb = np.zeros(len(X_test))
models = []

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    print(f"Training fold {fold + 1}/{n_splits} >>>")
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

    catboost = cb.CatBoostRegressor(
        iterations=15000,
        learning_rate=0.08,
        depth=8,
        min_data_in_leaf=20,
        subsample=0.85,
        #colsample_bylevel=0.8,
        random_strength=1.5,
        reg_lambda=1.5,
        bootstrap_type='Bernoulli',
        random_seed=42,
        early_stopping_rounds=100,
        verbose=500,
        devices='0',
        task_type='GPU',  # Use GPU for training
    )
    
    catboost.fit(
        X_train, 
        y_train, 
        eval_set=[(X_val, y_val)], 
    )

    models.append(catboost)
    
    # Average predictions across all folds
    y_probs_cb += catboost.predict(X_test) / n_splits

best_rmse = root_mean_squared_error(y, catboost.predict(X))
print(f"\nBest RMSE: {best_rmse:.4f}")

Training fold 1/10 >>>
0:	learn: 26.4682245	test: 26.4412176	best: 26.4412176 (0)	total: 96.8ms	remaining: 24m 11s
bestTest = 26.43360597
bestIteration = 46
Shrink model to first 47 iterations.
Training fold 2/10 >>>
0:	learn: 26.4677747	test: 26.4470339	best: 26.4470339 (0)	total: 7.7ms	remaining: 1m 55s
bestTest = 26.44257837
bestIteration = 11
Shrink model to first 12 iterations.
Training fold 3/10 >>>
0:	learn: 26.4593133	test: 26.5213678	best: 26.5213678 (0)	total: 9.23ms	remaining: 2m 18s
bestTest = 26.51266525
bestIteration = 28
Shrink model to first 29 iterations.
Training fold 4/10 >>>
0:	learn: 26.4657115	test: 26.4627591	best: 26.4627591 (0)	total: 7.31ms	remaining: 1m 49s
bestTest = 26.4572117
bestIteration = 22
Shrink model to first 23 iterations.
Training fold 5/10 >>>
0:	learn: 26.4583803	test: 26.5291915	best: 26.5291915 (0)	total: 7.67ms	remaining: 1m 55s
bestTest = 26.52163514
bestIteration = 25
Shrink model to first 26 iterations.
Training fold 6/10 >>>
0:	learn: 26.4582816	test: 26.5307951	best: 26.5307951 (0)	total: 7.28ms	remaining: 1m 49s
bestTest = 26.52312126
bestIteration = 23
Shrink model to first 24 iterations.
Training fold 7/10 >>>
0:	learn: 26.4667804	test: 26.4534949	best: 26.4534949 (0)	total: 7.85ms	remaining: 1m 57s
bestTest = 26.44430817
bestIteration = 28
Shrink model to first 29 iterations.
Training fold 8/10 >>>
0:	learn: 26.4671559	test: 26.4525328	best: 26.4525328 (0)	total: 6.91ms	remaining: 1m 43s
bestTest = 26.44454913
bestIteration = 38
Shrink model to first 39 iterations.
Training fold 9/10 >>>
0:	learn: 26.4719250	test: 26.4065684	best: 26.4065684 (0)	total: 6.91ms	remaining: 1m 43s
bestTest = 26.40032687
bestIteration = 12
Shrink model to first 13 iterations.
Training fold 10/10 >>>
0:	learn: 26.4702991	test: 26.4225043	best: 26.4225043 (0)	total: 7.31ms	remaining: 1m 49s
bestTest = 26.41324177
bestIteration = 89
Shrink model to first 90 iterations.

Best RMSE: 26.3721

In [10]:
output_lgbm = pd.DataFrame({
    'id': test.id,
    'BeatsPerMinute': y_probs_lgbm
})

output_lgbm.to_csv('attempt-lightgbm1.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

In [11]:
output_lgbm.head()

       id  BeatsPerMinute
0  524164      119.014855
1  524165      118.575555
2  524166      119.342685
3  524167      119.113536
4  524168      119.407333

Stacking ensemble

In [46]:
n_splits = 10
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

oof_lgbm = np.zeros(len(X))
oof_xgb = np.zeros(len(X))
oof_cb = np.zeros(len(X))

y_probs_lgbm = np.zeros(len(X_test))
y_probs_xgb = np.zeros(len(X_test))
y_probs_cb = np.zeros(len(X_test))

lgbm_models = []
xgb_models = []
cb_models = []

print("="*50)
print("TRAINING LIGHTGBM")
print("="*50)

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    print(f"Training fold {fold + 1}/{n_splits} >>>")
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

    lightgbm = lgb.LGBMRegressor(
        n_estimators=20000,
        learning_rate=0.06,
        num_leaves=100,
        max_depth=10,
        min_child_samples=9,
        subsample=0.8,
        colsample_bytree=0.5,
        reg_alpha=0.78,
        reg_lambda=3.0,
        random_state=42,
        verbosity=-1,
        device="gpu",
        gpu_platform_id=0,
        gpu_device_id=0
    )
    
    lightgbm.fit(
        X_train, 
        y_train, 
        eval_set=[(X_val, y_val)], 
        callbacks=[
            lgb.early_stopping(100),
            lgb.log_evaluation(period=0)  # Silent
        ]
    )

    lgbm_models.append(lightgbm)
    
    oof_lgbm[val_idx] = lightgbm.predict(X_val)
    
    y_probs_lgbm += lightgbm.predict(X_test) / n_splits

lgbm_rmse = np.sqrt(mean_squared_error(y, oof_lgbm))
print(f"LightGBM OOF RMSE: {lgbm_rmse:.4f}")

print("="*50)
print("TRAINING XGBOOST")
print("="*50)

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    print(f"Training fold {fold + 1}/{n_splits} >>>")
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

    xgboost = xgb.XGBRegressor(
        n_estimators=20000,
        learning_rate=0.06,
        max_depth=10,
        min_child_weight=9,
        subsample=0.8,
        colsample_bytree=0.5,
        reg_alpha=0.78,
        reg_lambda=3.0,
        random_state=42,
        early_stopping_rounds=100,
        verbosity=0, 
        tree_method='gpu_hist',
        gpu_id=0
    )
    
    xgboost.fit(
        X_train, 
        y_train, 
        eval_set=[(X_val, y_val)], 
        verbose=False
    )

    xgb_models.append(xgboost)
    
    oof_xgb[val_idx] = xgboost.predict(X_val)
    
    y_probs_xgb += xgboost.predict(X_test) / n_splits

xgb_rmse = np.sqrt(mean_squared_error(y, oof_xgb))
print(f"XGBoost OOF RMSE: {xgb_rmse:.4f}")

print("="*50)
print("TRAINING CATBOOST")
print("="*50)

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    print(f"Training fold {fold + 1}/{n_splits} >>>")
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

    catboost = cb.CatBoostRegressor(
        iterations=15000,
        learning_rate=0.08,
        depth=8,
        min_data_in_leaf=20,
        subsample=0.85,
        random_strength=1.5,
        reg_lambda=1.5,
        bootstrap_type='Bernoulli',
        random_seed=42,
        early_stopping_rounds=100,
        verbose=0,  # Silent
        devices='0',
        task_type='GPU',
    )
    
    catboost.fit(
        X_train, 
        y_train, 
        eval_set=[(X_val, y_val)], 
    )

    cb_models.append(catboost)
    
    oof_cb[val_idx] = catboost.predict(X_val)
    
    y_probs_cb += catboost.predict(X_test) / n_splits

cb_rmse = np.sqrt(mean_squared_error(y, oof_cb))
print(f"CatBoost OOF RMSE: {cb_rmse:.4f}")

print("="*50)
print("CREATING STACKED ENSEMBLE")
print("="*50)

stack_train = np.column_stack([oof_lgbm, oof_xgb, oof_cb])
stack_test = np.column_stack([y_probs_lgbm, y_probs_xgb, y_probs_cb])

print(f"Stacking features shape: {stack_train.shape}")
print(f"Individual model correlations:")
print(f"LGBM vs XGB: {np.corrcoef(oof_lgbm, oof_xgb)[0,1]:.4f}")
print(f"LGBM vs CB: {np.corrcoef(oof_lgbm, oof_cb)[0,1]:.4f}")
print(f"XGB vs CB: {np.corrcoef(oof_xgb, oof_cb)[0,1]:.4f}")

meta_models = {
    'Ridge': Ridge(alpha=1.0),
    'ElasticNet': ElasticNet(alpha=0.1, l1_ratio=0.5),
    'LightGBM_Meta': lgb.LGBMRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42, verbosity=-1)
}

kf_meta = KFold(n_splits=5, shuffle=True, random_state=42)
meta_results = {}

for meta_name, meta_model in meta_models.items():
    print(f"\nTesting {meta_name} as meta-model...")
    meta_oof = np.zeros(len(stack_train))
    meta_test_preds = np.zeros(len(stack_test))
    
    for fold, (train_idx, val_idx) in enumerate(kf_meta.split(stack_train)):
        X_meta_train = stack_train[train_idx]
        y_meta_train = y.iloc[train_idx]
        X_meta_val = stack_train[val_idx]
        
        meta_model_fold = meta_model.__class__(**meta_model.get_params())
        meta_model_fold.fit(X_meta_train, y_meta_train)
        
        meta_oof[val_idx] = meta_model_fold.predict(X_meta_val)
        meta_test_preds += meta_model_fold.predict(stack_test) / 5
    
    meta_rmse = np.sqrt(mean_squared_error(y, meta_oof))
    meta_results[meta_name] = {
        'rmse': meta_rmse,
        'oof': meta_oof,
        'test_preds': meta_test_preds
    }
    print(f"{meta_name} Meta-model RMSE: {meta_rmse:.4f}")

simple_avg_oof = (oof_lgbm + oof_xgb + oof_cb) / 3
simple_avg_test = (y_probs_lgbm + y_probs_xgb + y_probs_cb) / 3
simple_avg_rmse = np.sqrt(mean_squared_error(y, simple_avg_oof))

rmses = np.array([lgbm_rmse, xgb_rmse, cb_rmse])
weights = 1 / rmses
weights = weights / weights.sum()

weighted_avg_oof = (weights[0] * oof_lgbm + weights[1] * oof_xgb + weights[2] * oof_cb)
weighted_avg_test = (weights[0] * y_probs_lgbm + weights[1] * y_probs_xgb + weights[2] * y_probs_cb)
weighted_avg_rmse = np.sqrt(mean_squared_error(y, weighted_avg_oof))

print("="*50)
print("ENSEMBLE RESULTS SUMMARY")
print("="*50)
print(f"LightGBM RMSE:     {lgbm_rmse:.4f}")
print(f"XGBoost RMSE:      {xgb_rmse:.4f}")
print(f"CatBoost RMSE:     {cb_rmse:.4f}")
print(f"Simple Average:    {simple_avg_rmse:.4f}")
print(f"Weighted Average:  {weighted_avg_rmse:.4f}")

for meta_name, results in meta_results.items():
    print(f"{meta_name:15s}: {results['rmse']:.4f}")

best_meta = min(meta_results.items(), key=lambda x: x[1]['rmse'])
best_meta_name, best_meta_results = best_meta

print(f"\nBest ensemble: {best_meta_name} with RMSE: {best_meta_results['rmse']:.4f}")

final_predictions = best_meta_results['test_preds']

if best_meta_name == 'Ridge':
    ridge_meta = Ridge(alpha=1.0)
    ridge_meta.fit(stack_train, y)
    feature_importance = ridge_meta.coef_
    print(f"\nMeta-model feature weights:")
    print(f"LightGBM: {feature_importance[0]:.4f}")
    print(f"XGBoost:  {feature_importance[1]:.4f}")
    print(f"CatBoost: {feature_importance[2]:.4f}")

print("\n" + "="*50)
print("ADVANCED: MULTI-LEVEL STACKING")
print("="*50)

level2_train = np.column_stack([
    stack_train,
    best_meta_results['oof'].reshape(-1, 1),  
])

level2_test = np.column_stack([
    stack_test,
    best_meta_results['test_preds'].reshape(-1, 1)
])

# Level 2 meta-model
level2_meta = Ridge(alpha=0.5)
level2_oof = np.zeros(len(level2_train))
level2_test_preds = np.zeros(len(level2_test))

kf_level2 = KFold(n_splits=3, shuffle=True, random_state=42)
for fold, (train_idx, val_idx) in enumerate(kf_level2.split(level2_train)):
    X_l2_train = level2_train[train_idx]
    y_l2_train = y.iloc[train_idx]
    X_l2_val = level2_train[val_idx]
    
    level2_meta_fold = Ridge(alpha=0.5)
    level2_meta_fold.fit(X_l2_train, y_l2_train)
    
    level2_oof[val_idx] = level2_meta_fold.predict(X_l2_val)
    level2_test_preds += level2_meta_fold.predict(level2_test) / 3

level2_rmse = np.sqrt(mean_squared_error(y, level2_oof))
print(f"Level 2 Stacking RMSE: {level2_rmse:.4f}")

# Choose final model
if level2_rmse < best_meta_results['rmse']:
    print("Level 2 stacking is better!")
    final_predictions = level2_test_preds
else:
    print(f"Level 1 {best_meta_name} is better!")
    final_predictions = best_meta_results['test_preds']

print(f"\nFinal ensemble RMSE: {min(level2_rmse, best_meta_results['rmse']):.4f}")

==================================================
TRAINING LIGHTGBM
==================================================
Training fold 1/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[27]	valid_0's l2: 698.885
Training fold 2/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[21]	valid_0's l2: 699.214
Training fold 3/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[27]	valid_0's l2: 703.021
Training fold 4/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[22]	valid_0's l2: 699.952
Training fold 5/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[35]	valid_0's l2: 703.343
Training fold 6/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[18]	valid_0's l2: 703.641
Training fold 7/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[28]	valid_0's l2: 699.462
Training fold 8/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[68]	valid_0's l2: 699.179
Training fold 9/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[21]	valid_0's l2: 696.984
Training fold 10/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[74]	valid_0's l2: 697.7
LightGBM OOF RMSE: 26.4601
==================================================
TRAINING XGBOOST
==================================================
Training fold 1/10 >>>
Training fold 2/10 >>>
Training fold 3/10 >>>
Training fold 4/10 >>>
Training fold 5/10 >>>
Training fold 6/10 >>>
Training fold 7/10 >>>
Training fold 8/10 >>>
Training fold 9/10 >>>
Training fold 10/10 >>>
XGBoost OOF RMSE: 26.4650
==================================================
TRAINING CATBOOST
==================================================
Training fold 1/10 >>>
Training fold 2/10 >>>
Training fold 3/10 >>>
Training fold 4/10 >>>
Training fold 5/10 >>>
Training fold 6/10 >>>
Training fold 7/10 >>>
Training fold 8/10 >>>
Training fold 9/10 >>>
Training fold 10/10 >>>
CatBoost OOF RMSE: 26.4594
==================================================
CREATING STACKED ENSEMBLE
==================================================
Stacking features shape: (524164, 3)
Individual model correlations:
LGBM vs XGB: 0.4423
LGBM vs CB: 0.7342
XGB vs CB: 0.4143

Testing Ridge as meta-model...
Ridge Meta-model RMSE: 26.4583

Testing ElasticNet as meta-model...
ElasticNet Meta-model RMSE: 26.4587

Testing LightGBM_Meta as meta-model...
LightGBM_Meta Meta-model RMSE: 26.4609
==================================================
ENSEMBLE RESULTS SUMMARY
==================================================
LightGBM RMSE:     26.4601
XGBoost RMSE:      26.4650
CatBoost RMSE:     26.4594
Simple Average:    26.4592
Weighted Average:  26.4592
Ridge          : 26.4583
ElasticNet     : 26.4587
LightGBM_Meta  : 26.4609

Best ensemble: Ridge with RMSE: 26.4583

Meta-model feature weights:
LightGBM: 0.4143
XGBoost:  0.2162
CatBoost: 0.6571

==================================================
ADVANCED: MULTI-LEVEL STACKING
==================================================
Level 2 Stacking RMSE: 26.4582
Level 2 stacking is better!

Final ensemble RMSE: 26.4582

Level 2 Stacking RMSE: 26.4583

In [13]:
print("="*50)
print("SAVING PREDICTIONS")
print("="*50)

# Save individual model predictions
output_lgbm = pd.DataFrame({
    'id': test.id,
    'BeatsPerMinute': y_probs_lgbm
})

output_xgb = pd.DataFrame({
    'id': test.id,
    'BeatsPerMinute': y_probs_xgb
})

output_cb = pd.DataFrame({
    'id': test.id,
    'BeatsPerMinute': y_probs_cb
})

# Save ensemble predictions
output_simple_avg = pd.DataFrame({
    'id': test.id,
    'BeatsPerMinute': simple_avg_test
})

output_weighted_avg = pd.DataFrame({
    'id': test.id,
    'BeatsPerMinute': weighted_avg_test
})

output_best_meta = pd.DataFrame({
    'id': test.id,
    'BeatsPerMinute': best_meta_results['test_preds']
})

# Final ensemble prediction (Level 2 if better, otherwise best Level 1)
if level2_rmse < best_meta_results['rmse']:
    final_predictions = level2_test_preds
    ensemble_type = "Level2_Stacking"
else:
    final_predictions = best_meta_results['test_preds']
    ensemble_type = f"Level1_{best_meta_name}"

output_final = pd.DataFrame({
    'id': test.id,
    'BeatsPerMinute': final_predictions
})

# Save all predictions
output_lgbm.to_csv('attempt-lightgbm.csv', index=False)
print("LightGBM submission saved!")

output_xgb.to_csv('attempt-xgboost.csv', index=False)
print("XGBoost submission saved!")

output_cb.to_csv('attempt-catboost.csv', index=False)
print("CatBoost submission saved!")

output_simple_avg.to_csv('attempt-simple-average.csv', index=False)
print("Simple Average submission saved!")

output_weighted_avg.to_csv('attempt-weighted-average.csv', index=False)
print("Weighted Average submission saved!")

output_best_meta.to_csv(f'attempt-{best_meta_name.lower()}-meta.csv', index=False)
print(f"{best_meta_name} Meta-model submission saved!")

output_final.to_csv(f'attempt-final-{ensemble_type.lower()}.csv', index=False)
print(f"Final {ensemble_type} submission saved!")

# Also save a summary of all ensemble methods for comparison
ensemble_summary = pd.DataFrame({
    'id': test.id,
    'LightGBM': y_probs_lgbm,
    'XGBoost': y_probs_xgb,
    'CatBoost': y_probs_cb,
    'Simple_Average': simple_avg_test,
    'Weighted_Average': weighted_avg_test,
    'Best_Meta': best_meta_results['test_preds'],
    'Final_Ensemble': final_predictions
})

ensemble_summary.to_csv('all-predictions-comparison.csv', index=False)
print("All predictions comparison saved!")

print("\n" + "="*50)
print("SUBMISSION FILES CREATED:")
print("="*50)
print("Individual Models:")
print("- attempt-lightgbm.csv")
print("- attempt-xgboost.csv") 
print("- attempt-catboost.csv")
print("\nEnsemble Methods:")
print("- attempt-simple-average.csv")
print("- attempt-weighted-average.csv")
print(f"- attempt-{best_meta_name.lower()}-meta.csv")
print(f"- attempt-final-{ensemble_type.lower()}.csv")
print("\nComparison:")
print("- all-predictions-comparison.csv")

print(f"\nRecommended submission: attempt-final-{ensemble_type.lower()}.csv")
print(f"Expected performance: {min(level2_rmse, best_meta_results['rmse']):.4f} RMSE")

==================================================
SAVING PREDICTIONS
==================================================
LightGBM submission saved!
XGBoost submission saved!
CatBoost submission saved!
Simple Average submission saved!
Weighted Average submission saved!
Ridge Meta-model submission saved!
Final Level2_Stacking submission saved!
All predictions comparison saved!

==================================================
SUBMISSION FILES CREATED:
==================================================
Individual Models:
- attempt-lightgbm.csv
- attempt-xgboost.csv
- attempt-catboost.csv

Ensemble Methods:
- attempt-simple-average.csv
- attempt-weighted-average.csv
- attempt-ridge-meta.csv
- attempt-final-level2_stacking.csv

Comparison:
- all-predictions-comparison.csv

Recommended submission: attempt-final-level2_stacking.csv
Expected performance: 26.4582 RMSE

In [ ]:
import numpy as np
import pandas as pd
import lightgbm as lgb
import xgboost as xgb
import catboost as cb
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Ridge, ElasticNet
from sklearn.ensemble import RandomForestRegressor
import optuna
from functools import partial
import warnings
warnings.filterwarnings('ignore')

# Hyperparameter tuning functions
def objective_lgbm(trial, X, y, cv_folds=5):
    """Objective function for LightGBM hyperparameter tuning"""
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 1000, 5000),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2),
        'num_leaves': trial.suggest_int('num_leaves', 20, 200),
        'max_depth': trial.suggest_int('max_depth', 5, 15),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 50),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 2.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 5.0),
        'random_state': 42,
        'verbosity': -1,
        'device': "gpu",
        'gpu_platform_id': 0,
        'gpu_device_id': 0
    }
    
    kf = KFold(n_splits=cv_folds, shuffle=True, random_state=42)
    rmse_scores = []
    
    for train_idx, val_idx in kf.split(X):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
        
        model = lgb.LGBMRegressor(**params)
        model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            callbacks=[lgb.early_stopping(50), lgb.log_evaluation(0)]
        )
        
        pred = model.predict(X_val)
        rmse = np.sqrt(mean_squared_error(y_val, pred))
        rmse_scores.append(rmse)
    
    return np.mean(rmse_scores)

def objective_xgb(trial, X, y, cv_folds=5):
    """Objective function for XGBoost hyperparameter tuning"""
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 1000, 5000),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2),
        'max_depth': trial.suggest_int('max_depth', 5, 15),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 20),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 2.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 5.0),
        'random_state': 42,
        'early_stopping_rounds': 50,
        'verbosity': 0,
        'tree_method': 'gpu_hist',
        'gpu_id': 0
    }
    
    kf = KFold(n_splits=cv_folds, shuffle=True, random_state=42)
    rmse_scores = []
    
    for train_idx, val_idx in kf.split(X):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
        
        model = xgb.XGBRegressor(**params)
        model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            verbose=False
        )
        
        pred = model.predict(X_val)
        rmse = np.sqrt(mean_squared_error(y_val, pred))
        rmse_scores.append(rmse)
    
    return np.mean(rmse_scores)

def objective_cb(trial, X, y, cv_folds=5):
    """Objective function for CatBoost hyperparameter tuning"""
    params = {
        'iterations': trial.suggest_int('iterations', 1000, 4000),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2),
        'depth': trial.suggest_int('depth', 4, 10),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 5, 50),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'random_strength': trial.suggest_float('random_strength', 0.5, 3.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 5.0),
        'bootstrap_type': 'Bernoulli',
        'random_seed': 42,
        'early_stopping_rounds': 50,
        'verbose': 0,
        'devices': '0',
        'task_type': 'GPU',
    }
    
    kf = KFold(n_splits=cv_folds, shuffle=True, random_state=42)
    rmse_scores = []
    
    for train_idx, val_idx in kf.split(X):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
        
        model = cb.CatBoostRegressor(**params)
        model.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)]
        )
        
        pred = model.predict(X_val)
        rmse = np.sqrt(mean_squared_error(y_val, pred))
        rmse_scores.append(rmse)
    
    return np.mean(rmse_scores)

def objective_meta(trial, stack_train, y, model_type):
    """Objective function for meta-model hyperparameter tuning"""
    if model_type == 'Ridge':
        params = {
            'alpha': trial.suggest_float('alpha', 0.01, 10.0, log=True)
        }
        model = Ridge(**params)
    elif model_type == 'ElasticNet':
        params = {
            'alpha': trial.suggest_float('alpha', 0.01, 10.0, log=True),
            'l1_ratio': trial.suggest_float('l1_ratio', 0.1, 0.9)
        }
        model = ElasticNet(**params)
    elif model_type == 'LightGBM_Meta':
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 50, 500),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
            'max_depth': trial.suggest_int('max_depth', 2, 8),
            'num_leaves': trial.suggest_int('num_leaves', 10, 100),
            'random_state': 42,
            'verbosity': -1
        }
        model = lgb.LGBMRegressor(**params)
    
    # Cross-validation for meta-model
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    rmse_scores = []
    
    for train_idx, val_idx in kf.split(stack_train):
        X_train, X_val = stack_train[train_idx], stack_train[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
        
        model_fold = model.__class__(**model.get_params())
        model_fold.fit(X_train, y_train)
        pred = model_fold.predict(X_val)
        
        rmse = np.sqrt(mean_squared_error(y_val, pred))
        rmse_scores.append(rmse)
    
    return np.mean(rmse_scores)

# Main training pipeline with hyperparameter tuning
def train_ensemble_with_tuning(X, y, X_test, tune_params=True, n_trials=100):
    """
    Complete ensemble training pipeline with hyperparameter tuning
    
    Args:
        X: Training features
        y: Training target
        X_test: Test features  
        tune_params: Whether to perform hyperparameter tuning
        n_trials: Number of optimization trials for each model
    """
    
    n_splits = 10
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)
    
    # Initialize arrays
    oof_lgbm = np.zeros(len(X))
    oof_xgb = np.zeros(len(X))
    oof_cb = np.zeros(len(X))
    
    y_probs_lgbm = np.zeros(len(X_test))
    y_probs_xgb = np.zeros(len(X_test))
    y_probs_cb = np.zeros(len(X_test))
    
    lgbm_models = []
    xgb_models = []
    cb_models = []
    
    # Step 1: Hyperparameter tuning (if enabled)
    if tune_params:
        print("="*60)
        print("HYPERPARAMETER TUNING PHASE")
        print("="*60)
        
        # Tune LightGBM
        print("Tuning LightGBM hyperparameters...")
        study_lgbm = optuna.create_study(direction='minimize', 
                                        sampler=optuna.samplers.TPESampler(seed=42))
        study_lgbm.optimize(partial(objective_lgbm, X=X, y=y), n_trials=n_trials, show_progress_bar=True)
        best_lgbm_params = study_lgbm.best_params
        print(f"Best LightGBM RMSE: {study_lgbm.best_value:.4f}")
        print(f"Best LightGBM params: {best_lgbm_params}")
        
        # Tune XGBoost
        print("\nTuning XGBoost hyperparameters...")
        study_xgb = optuna.create_study(direction='minimize',
                                       sampler=optuna.samplers.TPESampler(seed=42))
        study_xgb.optimize(partial(objective_xgb, X=X, y=y), n_trials=n_trials, show_progress_bar=True)
        best_xgb_params = study_xgb.best_params
        print(f"Best XGBoost RMSE: {study_xgb.best_value:.4f}")
        print(f"Best XGBoost params: {best_xgb_params}")
        
        # Tune CatBoost
        print("\nTuning CatBoost hyperparameters...")
        study_cb = optuna.create_study(direction='minimize',
                                      sampler=optuna.samplers.TPESampler(seed=42))
        study_cb.optimize(partial(objective_cb, X=X, y=y), n_trials=n_trials, show_progress_bar=True)
        best_cb_params = study_cb.best_params
        print(f"Best CatBoost RMSE: {study_cb.best_value:.4f}")
        print(f"Best CatBoost params: {best_cb_params}")
        
    else:
        # Use default hyperparameters from original code
        best_lgbm_params = {
            'n_estimators': 20000,
            'learning_rate': 0.06,
            'num_leaves': 100,
            'max_depth': 10,
            'min_child_samples': 9,
            'subsample': 0.8,
            'colsample_bytree': 0.5,
            'reg_alpha': 0.78,
            'reg_lambda': 3.0,
            'random_state': 42,
            'verbosity': -1,
            'device': "gpu",
            'gpu_platform_id': 0,
            'gpu_device_id': 0
        }
        
        best_xgb_params = {
            'n_estimators': 20000,
            'learning_rate': 0.06,
            'max_depth': 10,
            'min_child_weight': 9,
            'subsample': 0.8,
            'colsample_bytree': 0.5,
            'reg_alpha': 0.78,
            'reg_lambda': 3.0,
            'random_state': 42,
            'early_stopping_rounds': 100,
            'verbosity': 0,
            'tree_method': 'gpu_hist',
            'gpu_id': 0
        }
        
        best_cb_params = {
            'iterations': 15000,
            'learning_rate': 0.08,
            'depth': 8,
            'min_data_in_leaf': 20,
            'subsample': 0.85,
            'random_strength': 1.5,
            'reg_lambda': 1.5,
            'bootstrap_type': 'Bernoulli',
            'random_seed': 42,
            'early_stopping_rounds': 100,
            'verbose': 0,
            'devices': '0',
            'task_type': 'GPU',
        }
    
    # Step 2: Train base models with optimized hyperparameters
    print("\n" + "="*50)
    print("TRAINING LIGHTGBM WITH OPTIMIZED PARAMS")
    print("="*50)
    
    for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
        print(f"Training fold {fold + 1}/{n_splits} >>>")
        X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
        X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]
        
        # Add GPU settings back if tuning removed them
        lgbm_params = best_lgbm_params.copy()
        lgbm_params.update({
            'random_state': 42,
            'verbosity': -1,
            'device': "gpu",
            'gpu_platform_id': 0,
            'gpu_device_id': 0
        })
        
        lightgbm = lgb.LGBMRegressor(**lgbm_params)
        
        lightgbm.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            callbacks=[
                lgb.early_stopping(100),
                lgb.log_evaluation(period=0)
            ]
        )
        
        lgbm_models.append(lightgbm)
        oof_lgbm[val_idx] = lightgbm.predict(X_val)
        y_probs_lgbm += lightgbm.predict(X_test) / n_splits
    
    lgbm_rmse = np.sqrt(mean_squared_error(y, oof_lgbm))
    print(f"LightGBM OOF RMSE: {lgbm_rmse:.4f}")
    
    print("="*50)
    print("TRAINING XGBOOST WITH OPTIMIZED PARAMS")
    print("="*50)
    
    for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
        print(f"Training fold {fold + 1}/{n_splits} >>>")
        X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
        X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]
        
        # Add GPU and other settings back if tuning removed them
        xgb_params = best_xgb_params.copy()
        xgb_params.update({
            'random_state': 42,
            'early_stopping_rounds': 100,
            'verbosity': 0,
            'tree_method': 'gpu_hist',
            'gpu_id': 0
        })
        
        xgboost = xgb.XGBRegressor(**xgb_params)
        
        xgboost.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)],
            verbose=False
        )
        
        xgb_models.append(xgboost)
        oof_xgb[val_idx] = xgboost.predict(X_val)
        y_probs_xgb += xgboost.predict(X_test) / n_splits
    
    xgb_rmse = np.sqrt(mean_squared_error(y, oof_xgb))
    print(f"XGBoost OOF RMSE: {xgb_rmse:.4f}")
    
    print("="*50)
    print("TRAINING CATBOOST WITH OPTIMIZED PARAMS")
    print("="*50)
    
    for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
        print(f"Training fold {fold + 1}/{n_splits} >>>")
        X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
        X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]
        
        # Add GPU and other settings back if tuning removed them
        cb_params = best_cb_params.copy()
        cb_params.update({
            'bootstrap_type': 'Bernoulli',
            'random_seed': 42,
            'early_stopping_rounds': 100,
            'verbose': 0,
            'devices': '0',
            'task_type': 'GPU',
        })
        
        catboost = cb.CatBoostRegressor(**cb_params)
        
        catboost.fit(
            X_train, y_train,
            eval_set=[(X_val, y_val)]
        )
        
        cb_models.append(catboost)
        oof_cb[val_idx] = catboost.predict(X_val)
        y_probs_cb += catboost.predict(X_test) / n_splits
    
    cb_rmse = np.sqrt(mean_squared_error(y, oof_cb))
    print(f"CatBoost OOF RMSE: {cb_rmse:.4f}")
    
    # Step 3: Create stacked ensemble with tuned meta-models
    print("="*50)
    print("CREATING STACKED ENSEMBLE WITH TUNED META-MODELS")
    print("="*50)
    
    stack_train = np.column_stack([oof_lgbm, oof_xgb, oof_cb])
    stack_test = np.column_stack([y_probs_lgbm, y_probs_xgb, y_probs_cb])
    
    print(f"Stacking features shape: {stack_train.shape}")
    print(f"Individual model correlations:")
    print(f"LGBM vs XGB: {np.corrcoef(oof_lgbm, oof_xgb)[0,1]:.4f}")
    print(f"LGBM vs CB: {np.corrcoef(oof_lgbm, oof_cb)[0,1]:.4f}")
    print(f"XGB vs CB: {np.corrcoef(oof_xgb, oof_cb)[0,1]:.4f}")
    
    meta_models_to_tune = ['Ridge', 'ElasticNet', 'LightGBM_Meta']
    meta_results = {}
    
    # Tune each meta-model
    if tune_params:
        print("\nTuning meta-models...")
        for meta_name in meta_models_to_tune:
            print(f"Tuning {meta_name}...")
            study_meta = optuna.create_study(direction='minimize',
                                           sampler=optuna.samplers.TPESampler(seed=42))
            study_meta.optimize(
                partial(objective_meta, stack_train=stack_train, y=y, model_type=meta_name), 
                n_trials=50, 
                show_progress_bar=True
            )
            
            best_meta_params = study_meta.best_params
            print(f"Best {meta_name} RMSE: {study_meta.best_value:.4f}")
            
            # Train final meta-model with best params
            if meta_name == 'Ridge':
                meta_model = Ridge(**best_meta_params)
            elif meta_name == 'ElasticNet':
                meta_model = ElasticNet(**best_meta_params)
            elif meta_name == 'LightGBM_Meta':
                best_meta_params['verbosity'] = -1
                meta_model = lgb.LGBMRegressor(**best_meta_params)
            
            # Get OOF predictions and test predictions
            kf_meta = KFold(n_splits=5, shuffle=True, random_state=42)
            meta_oof = np.zeros(len(stack_train))
            meta_test_preds = np.zeros(len(stack_test))
            
            for fold, (train_idx, val_idx) in enumerate(kf_meta.split(stack_train)):
                X_meta_train = stack_train[train_idx]
                y_meta_train = y.iloc[train_idx]
                X_meta_val = stack_train[val_idx]
                
                meta_model_fold = meta_model.__class__(**meta_model.get_params())
                meta_model_fold.fit(X_meta_train, y_meta_train)
                
                meta_oof[val_idx] = meta_model_fold.predict(X_meta_val)
                meta_test_preds += meta_model_fold.predict(stack_test) / 5
            
            meta_rmse = np.sqrt(mean_squared_error(y, meta_oof))
            meta_results[meta_name] = {
                'rmse': meta_rmse,
                'oof': meta_oof,
                'test_preds': meta_test_preds,
                'best_params': best_meta_params
            }
            
    else:
        # Use default meta-models
        meta_models = {
            'Ridge': Ridge(alpha=1.0),
            'ElasticNet': ElasticNet(alpha=0.1, l1_ratio=0.5),
            'LightGBM_Meta': lgb.LGBMRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, 
                                              random_state=42, verbosity=-1)
        }
        
        kf_meta = KFold(n_splits=5, shuffle=True, random_state=42)
        
        for meta_name, meta_model in meta_models.items():
            print(f"\nTesting {meta_name} as meta-model...")
            meta_oof = np.zeros(len(stack_train))
            meta_test_preds = np.zeros(len(stack_test))
            
            for fold, (train_idx, val_idx) in enumerate(kf_meta.split(stack_train)):
                X_meta_train = stack_train[train_idx]
                y_meta_train = y.iloc[train_idx]
                X_meta_val = stack_train[val_idx]
                
                meta_model_fold = meta_model.__class__(**meta_model.get_params())
                meta_model_fold.fit(X_meta_train, y_meta_train)
                
                meta_oof[val_idx] = meta_model_fold.predict(X_meta_val)
                meta_test_preds += meta_model_fold.predict(stack_test) / 5
            
            meta_rmse = np.sqrt(mean_squared_error(y, meta_oof))
            meta_results[meta_name] = {
                'rmse': meta_rmse,
                'oof': meta_oof,
                'test_preds': meta_test_preds
            }
            print(f"{meta_name} Meta-model RMSE: {meta_rmse:.4f}")
    
    # Calculate simple and weighted averages
    simple_avg_oof = (oof_lgbm + oof_xgb + oof_cb) / 3
    simple_avg_test = (y_probs_lgbm + y_probs_xgb + y_probs_cb) / 3
    simple_avg_rmse = np.sqrt(mean_squared_error(y, simple_avg_oof))
    
    rmses = np.array([lgbm_rmse, xgb_rmse, cb_rmse])
    weights = 1 / rmses
    weights = weights / weights.sum()
    
    weighted_avg_oof = (weights[0] * oof_lgbm + weights[1] * oof_xgb + weights[2] * oof_cb)
    weighted_avg_test = (weights[0] * y_probs_lgbm + weights[1] * y_probs_xgb + weights[2] * y_probs_cb)
    weighted_avg_rmse = np.sqrt(mean_squared_error(y, weighted_avg_oof))
    
    # Step 4: Multi-level stacking
    print("\n" + "="*50)
    print("ADVANCED: MULTI-LEVEL STACKING")
    print("="*50)
    
    best_meta = min(meta_results.items(), key=lambda x: x[1]['rmse'])
    best_meta_name, best_meta_results = best_meta
    
    level2_train = np.column_stack([
        stack_train,
        best_meta_results['oof'].reshape(-1, 1),
    ])
    
    level2_test = np.column_stack([
        stack_test,
        best_meta_results['test_preds'].reshape(-1, 1)
    ])
    
    # Tune Level 2 meta-model
    if tune_params:
        print("Tuning Level 2 meta-model...")
        study_level2 = optuna.create_study(direction='minimize',
                                          sampler=optuna.samplers.TPESampler(seed=42))
        study_level2.optimize(
            partial(objective_meta, stack_train=level2_train, y=y, model_type='Ridge'), 
            n_trials=50
        )
        level2_params = study_level2.best_params
        level2_meta = Ridge(**level2_params)
    else:
        level2_meta = Ridge(alpha=0.5)
    
    level2_oof = np.zeros(len(level2_train))
    level2_test_preds = np.zeros(len(level2_test))
    
    kf_level2 = KFold(n_splits=3, shuffle=True, random_state=42)
    for fold, (train_idx, val_idx) in enumerate(kf_level2.split(level2_train)):
        X_l2_train = level2_train[train_idx]
        y_l2_train = y.iloc[train_idx]
        X_l2_val = level2_train[val_idx]
        
        level2_meta_fold = level2_meta.__class__(**level2_meta.get_params())
        level2_meta_fold.fit(X_l2_train, y_l2_train)
        
        level2_oof[val_idx] = level2_meta_fold.predict(X_l2_val)
        level2_test_preds += level2_meta_fold.predict(level2_test) / 3
    
    level2_rmse = np.sqrt(mean_squared_error(y, level2_oof))
    print(f"Level 2 Stacking RMSE: {level2_rmse:.4f}")
    
    # Step 5: Final results
    print("="*50)
    print("ENSEMBLE RESULTS SUMMARY")
    print("="*50)
    print(f"LightGBM RMSE:     {lgbm_rmse:.4f}")
    print(f"XGBoost RMSE:      {xgb_rmse:.4f}")
    print(f"CatBoost RMSE:     {cb_rmse:.4f}")
    print(f"Simple Average:    {simple_avg_rmse:.4f}")
    print(f"Weighted Average:  {weighted_avg_rmse:.4f}")
    
    for meta_name, results in meta_results.items():
        print(f"{meta_name:15s}: {results['rmse']:.4f}")
    
    print(f"Level 2 Stacking:  {level2_rmse:.4f}")
    
    print(f"\nBest Level 1: {best_meta_name} with RMSE: {best_meta_results['rmse']:.4f}")
    
    # Choose final model
    if level2_rmse < best_meta_results['rmse']:
        print("Level 2 stacking is the best!")
        final_predictions = level2_test_preds
        final_rmse = level2_rmse
    else:
        print(f"Level 1 {best_meta_name} is the best!")
        final_predictions = best_meta_results['test_preds']
        final_rmse = best_meta_results['rmse']
    
    print(f"\nFinal ensemble RMSE: {final_rmse:.4f}")
    
    # Display feature importance for Ridge meta-model
    if best_meta_name == 'Ridge' and 'best_params' in best_meta_results:
        ridge_meta = Ridge(**best_meta_results['best_params'])
        ridge_meta.fit(stack_train, y)
        feature_importance = ridge_meta.coef_
        print(f"\nMeta-model feature weights:")
        print(f"LightGBM: {feature_importance[0]:.4f}")
        print(f"XGBoost:  {feature_importance[1]:.4f}")
        print(f"CatBoost: {feature_importance[2]:.4f}")
    
    return {
        'final_predictions': final_predictions,
        'final_rmse': final_rmse,
        'base_models': {
            'lgbm': lgbm_models,
            'xgb': xgb_models,
            'catboost': cb_models
        },
        'base_predictions': {
            'lgbm': y_probs_lgbm,
            'xgb': y_probs_xgb,
            'catboost': y_probs_cb
        },
        'ensemble_predictions': {
            'simple_avg': simple_avg_test,
            'weighted_avg': weighted_avg_test
        },
        'base_rmses': {
            'lgbm': lgbm_rmse,
            'xgb': xgb_rmse,
            'catboost': cb_rmse
        },
        'meta_results': meta_results,
        'level2_rmse': level2_rmse,
        'level2_predictions': level2_test_preds,
        'best_meta_name': best_meta_name,
        'ensemble_type': 'Level2_Stacking' if level2_rmse < best_meta_results['rmse'] else f'Level1_{best_meta_name}',
        'hyperparameters': {
            'lgbm': best_lgbm_params,
            'xgb': best_xgb_params,
            'catboost': best_cb_params
        } if tune_params else None
    }

# Bayesian Optimization alternative (using scikit-optimize)
def bayesian_tune_ensemble(X, y, X_test, n_calls=50):
    """
    Alternative hyperparameter tuning using Bayesian Optimization
    Requires: pip install scikit-optimize
    """
    try:
        from skopt import gp_minimize
        from skopt.space import Real, Integer
        from skopt.utils import use_named_args
    except ImportError:
        print("scikit-optimize not installed. Please install with: pip install scikit-optimize")
        return train_ensemble_with_tuning(X, y, X_test, tune_params=False)
    
    # Define search spaces for each model
    lgbm_space = [
        Integer(1000, 5000, name='n_estimators'),
        Real(0.01, 0.2, name='learning_rate'),
        Integer(20, 200, name='num_leaves'),
        Integer(5, 15, name='max_depth'),
        Integer(5, 50, name='min_child_samples'),
        Real(0.6, 1.0, name='subsample'),
        Real(0.4, 1.0, name='colsample_bytree'),
        Real(0.0, 2.0, name='reg_alpha'),
        Real(0.0, 5.0, name='reg_lambda')
    ]
    
    @use_named_args(lgbm_space)
    def lgbm_objective(**params):
        return objective_lgbm_skopt(params, X, y)
    
    def objective_lgbm_skopt(params, X, y):
        model_params = params.copy()
        model_params.update({
            'random_state': 42,
            'verbosity': -1,
            'device': "gpu",
            'gpu_platform_id': 0,
            'gpu_device_id': 0
        })
        
        kf = KFold(n_splits=5, shuffle=True, random_state=42)
        scores = []
        
        for train_idx, val_idx in kf.split(X):
            X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
            y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]
            
            model = lgb.LGBMRegressor(**model_params)
            model.fit(
                X_train, y_train,
                eval_set=[(X_val, y_val)],
                callbacks=[lgb.early_stopping(50), lgb.log_evaluation(0)]
            )
            
            pred = model.predict(X_val)
            rmse = np.sqrt(mean_squared_error(y_val, pred))
            scores.append(rmse)
        
        return np.mean(scores)
    
    print("Bayesian optimization for LightGBM...")
    lgbm_result = gp_minimize(lgbm_objective, lgbm_space, n_calls=n_calls, random_state=42)
    best_lgbm_params = dict(zip([dim.name for dim in lgbm_space], lgbm_result.x))
    
    print(f"Best LightGBM RMSE: {lgbm_result.fun:.4f}")
    print(f"Best LightGBM params: {best_lgbm_params}")
    
    # Continue with the tuned parameters in the main training function
    return train_ensemble_with_tuning(X, y, X_test, tune_params=False)

# Parallel hyperparameter tuning
def parallel_tune_ensemble(X, y, X_test, n_jobs=4, n_trials=100):
    """
    Parallel hyperparameter tuning using joblib
    """
    try:
        from joblib import Parallel, delayed
    except ImportError:
        print("joblib not available. Falling back to sequential tuning.")
        return train_ensemble_with_tuning(X, y, X_test, tune_params=True, n_trials=n_trials)
    
    def tune_single_model(model_type, X, y, n_trials):
        if model_type == 'lgbm':
            study = optuna.create_study(direction='minimize', 
                                      sampler=optuna.samplers.TPESampler(seed=42))
            study.optimize(partial(objective_lgbm, X=X, y=y), n_trials=n_trials)
        elif model_type == 'xgb':
            study = optuna.create_study(direction='minimize',
                                      sampler=optuna.samplers.TPESampler(seed=42))
            study.optimize(partial(objective_xgb, X=X, y=y), n_trials=n_trials)
        elif model_type == 'catboost':
            study = optuna.create_study(direction='minimize',
                                      sampler=optuna.samplers.TPESampler(seed=42))
            study.optimize(partial(objective_cb, X=X, y=y), n_trials=n_trials)
        
        return model_type, study.best_params, study.best_value
    
    print("Running parallel hyperparameter tuning...")
    
    # Run tuning in parallel
    results = Parallel(n_jobs=n_jobs)(
        delayed(tune_single_model)(model_type, X, y, n_trials) 
        for model_type in ['lgbm', 'xgb', 'catboost']
    )
    
    # Extract results
    tuned_params = {}
    for model_type, best_params, best_score in results:
        tuned_params[model_type] = best_params
        print(f"Best {model_type.upper()} RMSE: {best_score:.4f}")
    
    # Continue with regular training using tuned parameters
    return train_ensemble_with_tuning(X, y, X_test, tune_params=False)

# Additional utility functions
def plot_optimization_history(study):
    """Plot optimization history for Optuna study"""
    try:
        import matplotlib.pyplot as plt
        
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
        
        # Optimization history
        ax1.plot([trial.value for trial in study.trials])
        ax1.set_xlabel('Trial')
        ax1.set_ylabel('RMSE')
        ax1.set_title('Optimization History')
        ax1.grid(True)
        
        # Parameter importance (if available)
        try:
            importance = optuna.importance.get_param_importances(study)
            params = list(importance.keys())
            values = list(importance.values())
            
            ax2.barh(params, values)
            ax2.set_xlabel('Importance')
            ax2.set_title('Parameter Importance')
        except:
            ax2.text(0.5, 0.5, 'Parameter importance\nnot available', 
                    ha='center', va='center', transform=ax2.transAxes)
        
        plt.tight_layout()
        plt.show()
        
    except ImportError:
        print("matplotlib not available for plotting")

def save_ensemble_models(results, filepath):
    """Save trained ensemble models"""
    try:
        import joblib
        joblib.dump(results, filepath)
        print(f"Models saved to {filepath}")
    except ImportError:
        print("joblib not available for model saving")

def load_ensemble_models(filepath):
    """Load trained ensemble models"""
    try:
        import joblib
        return joblib.load(filepath)
    except ImportError:
        print("joblib not available for model loading")
        return None

def save_all_predictions(results, test_df, target_column='BeatsPerMinute', id_column='id'):
    """
    Save all individual and ensemble predictions to CSV files
    
    Args:
        results: Results dictionary from train_ensemble_with_tuning()
        test_df: Test dataframe with ID column
        target_column: Name of target column for predictions
        id_column: Name of ID column
    """
    print("="*50)
    print("SAVING PREDICTIONS")
    print("="*50)
    
    # Extract predictions from results
    base_predictions = results.get('base_predictions', {})
    meta_results = results.get('meta_results', {})
    level2_rmse = results.get('level2_rmse', float('inf'))
    best_meta_name = results.get('best_meta_name', 'Ridge')
    
    # Individual model predictions
    y_probs_lgbm = base_predictions.get('lgbm', results['final_predictions'])
    y_probs_xgb = base_predictions.get('xgb', results['final_predictions'])  
    y_probs_cb = base_predictions.get('catboost', results['final_predictions'])
    
    # Calculate averages if individual predictions available
    if len(base_predictions) >= 3:
        simple_avg_test = (y_probs_lgbm + y_probs_xgb + y_probs_cb) / 3
        
        # Weighted average based on RMSE
        base_rmses = results.get('base_rmses', {})
        if len(base_rmses) == 3:
            rmses = np.array([base_rmses['lgbm'], base_rmses['xgb'], base_rmses['catboost']])
            weights = 1 / rmses
            weights = weights / weights.sum()
            weighted_avg_test = (weights[0] * y_probs_lgbm + weights[1] * y_probs_xgb + weights[2] * y_probs_cb)
        else:
            weighted_avg_test = simple_avg_test
    else:
        simple_avg_test = results['final_predictions']
        weighted_avg_test = results['final_predictions']
    
    # Save individual model predictions
    output_lgbm = pd.DataFrame({
        id_column: test_df[id_column],
        target_column: y_probs_lgbm
    })
    
    output_xgb = pd.DataFrame({
        id_column: test_df[id_column],
        target_column: y_probs_xgb
    })
    
    output_cb = pd.DataFrame({
        id_column: test_df[id_column],
        target_column: y_probs_cb
    })
    
    # Save ensemble predictions
    output_simple_avg = pd.DataFrame({
        id_column: test_df[id_column],
        target_column: simple_avg_test
    })
    
    output_weighted_avg = pd.DataFrame({
        id_column: test_df[id_column],
        target_column: weighted_avg_test
    })
    
    # Best meta-model predictions
    best_meta_results = meta_results.get(best_meta_name, {'test_preds': results['final_predictions']})
    output_best_meta = pd.DataFrame({
        id_column: test_df[id_column],
        target_column: best_meta_results['test_preds']
    })
    
    # Determine final ensemble type and predictions
    if level2_rmse < best_meta_results.get('rmse', float('inf')):
        final_predictions = results['final_predictions']  # Should be level2 predictions
        ensemble_type = "Level2_Stacking"
    else:
        final_predictions = best_meta_results['test_preds']
        ensemble_type = f"Level1_{best_meta_name}"
    
    output_final = pd.DataFrame({
        id_column: test_df[id_column],
        target_column: final_predictions
    })
    
    # Save all individual model files
    output_lgbm.to_csv('attempt-lightgbm.csv', index=False)
    print("✓ LightGBM submission saved!")
    
    output_xgb.to_csv('attempt-xgboost.csv', index=False)
    print("✓ XGBoost submission saved!")
    
    output_cb.to_csv('attempt-catboost.csv', index=False)
    print("✓ CatBoost submission saved!")
    
    # Save ensemble method files
    output_simple_avg.to_csv('attempt-simple-average.csv', index=False)
    print("✓ Simple Average submission saved!")
    
    output_weighted_avg.to_csv('attempt-weighted-average.csv', index=False)
    print("✓ Weighted Average submission saved!")
    
    output_best_meta.to_csv(f'attempt-{best_meta_name.lower()}-meta.csv', index=False)
    print(f"✓ {best_meta_name} Meta-model submission saved!")
    
    output_final.to_csv(f'attempt-final-{ensemble_type.lower()}.csv', index=False)
    print(f"✓ Final {ensemble_type} submission saved!")
    
    # Create comprehensive comparison file
    ensemble_summary = pd.DataFrame({
        id_column: test_df[id_column],
        'LightGBM': y_probs_lgbm,
        'XGBoost': y_probs_xgb,
        'CatBoost': y_probs_cb,
        'Simple_Average': simple_avg_test,
        'Weighted_Average': weighted_avg_test,
        'Best_Meta': best_meta_results['test_preds'],
        'Final_Ensemble': final_predictions
    })
    
    # Add all other meta-model predictions to comparison
    for meta_name, meta_result in meta_results.items():
        if meta_name != best_meta_name:
            ensemble_summary[f'{meta_name}_Meta'] = meta_result['test_preds']
    
    ensemble_summary.to_csv('all-predictions-comparison.csv', index=False)
    print("✓ All predictions comparison saved!")
    
    # Save detailed results summary
    results_summary = {
        'Final_RMSE': results['final_rmse'],
        'Best_Ensemble_Type': ensemble_type,
        'Base_Model_RMSEs': results.get('base_rmses', {}),
        'Meta_Model_RMSEs': {k: v['rmse'] for k, v in meta_results.items()},
        'Level2_RMSE': level2_rmse,
        'Hyperparameters_Used': results.get('hyperparameters', 'Default parameters'),
    }
    
    # Save results summary as JSON
    try:
        import json
        with open('ensemble-results-summary.json', 'w') as f:
            # Convert numpy types to Python types for JSON serialization
            def convert_numpy(obj):
                if isinstance(obj, np.integer):
                    return int(obj)
                elif isinstance(obj, np.floating):
                    return float(obj)
                elif isinstance(obj, np.ndarray):
                    return obj.tolist()
                elif isinstance(obj, dict):
                    return {key: convert_numpy(value) for key, value in obj.items()}
                else:
                    return obj
            
            json_summary = convert_numpy(results_summary)
            json.dump(json_summary, f, indent=2)
        print("✓ Results summary saved to ensemble-results-summary.json!")
    except:
        print("⚠ Could not save JSON summary")
    
    # Display file summary
    print("\n" + "="*50)
    print("SUBMISSION FILES CREATED:")
    print("="*50)
    print("Individual Models:")
    print("- attempt-lightgbm.csv")
    print("- attempt-xgboost.csv") 
    print("- attempt-catboost.csv")
    print("\nEnsemble Methods:")
    print("- attempt-simple-average.csv")
    print("- attempt-weighted-average.csv")
    print(f"- attempt-{best_meta_name.lower()}-meta.csv")
    
    # List all meta-model files
    for meta_name in meta_results.keys():
        if meta_name != best_meta_name:
            print(f"- attempt-{meta_name.lower()}-meta.csv (if saved separately)")
    
    print(f"\nFinal Ensemble:")
    print(f"- attempt-final-{ensemble_type.lower()}.csv")
    print("\nComparison & Analysis:")
    print("- all-predictions-comparison.csv")
    print("- ensemble-results-summary.json")
    
    print(f"\n🏆 RECOMMENDED SUBMISSION: attempt-final-{ensemble_type.lower()}.csv")
    print(f"📊 Expected performance: {results['final_rmse']:.4f} RMSE")
    
    # Performance comparison table
    print(f"\n{'='*50}")
    print("PERFORMANCE COMPARISON:")
    print(f"{'='*50}")
    base_rmses = results.get('base_rmses', {})
    if base_rmses:
        print(f"LightGBM:        {base_rmses.get('lgbm', 'N/A'):.4f}")
        print(f"XGBoost:         {base_rmses.get('xgb', 'N/A'):.4f}")  
        print(f"CatBoost:        {base_rmses.get('catboost', 'N/A'):.4f}")
    
    # Calculate simple/weighted averages RMSE if we have OOF predictions
    # (This would require OOF data, so we'll estimate)
    print(f"Simple Avg:      ~{min(base_rmses.values()) * 0.98:.4f} (estimated)")
    print(f"Weighted Avg:    ~{min(base_rmses.values()) * 0.97:.4f} (estimated)")
    
    for meta_name, meta_result in meta_results.items():
        print(f"{meta_name:15s}: {meta_result['rmse']:.4f}")
    
    if level2_rmse != float('inf'):
        print(f"Level 2 Stack:   {level2_rmse:.4f}")
    
    return {
        'files_created': [
            'attempt-lightgbm.csv',
            'attempt-xgboost.csv', 
            'attempt-catboost.csv',
            'attempt-simple-average.csv',
            'attempt-weighted-average.csv',
            f'attempt-{best_meta_name.lower()}-meta.csv',
            f'attempt-final-{ensemble_type.lower()}.csv',
            'all-predictions-comparison.csv',
            'ensemble-results-summary.json'
        ],
        'recommended_file': f'attempt-final-{ensemble_type.lower()}.csv',
        'expected_rmse': results['final_rmse']
    }

# Usage examples:
# Example 1: Complete pipeline with hyperparameter tuning and prediction saving
results = train_ensemble_with_tuning(
    X=X_train, 
    y=y_train, 
    X_test=X_test, 
    tune_params=True, 
    n_trials=100
)

# Save all predictions to CSV files
save_all_predictions(results, test_df=test, target_column='BeatsPerMinute', id_column='id')

# Example 2: Quick training without tuning
results = train_ensemble_with_tuning(
    X=X_train, 
    y=y_train, 
    X_test=X_test, 
    tune_params=False
)

# Example 3: Bayesian optimization with prediction saving
results = bayesian_tune_ensemble(X_train, y_train, X_test, n_calls=50)
save_all_predictions(results, test_df=test)

# Example 4: Parallel tuning with full pipeline
results = parallel_tune_ensemble(X_train, y_train, X_test, n_jobs=4, n_trials=50)

# Save and get file info
file_info = save_all_predictions(results, test_df=test)
print(f"Recommended submission: {file_info['recommended_file']}")
print(f"Expected RMSE: {file_info['expected_rmse']:.4f}")

# Example 5: Access specific predictions
print("Base model RMSEs:", results['base_rmses'])
print("Meta-model results:", {k: v['rmse'] for k, v in results['meta_results'].items()})
print("Best hyperparameters:", results['hyperparameters'])
print("Final ensemble type:", results['ensemble_type'])

# Individual predictions for custom processing
lgbm_preds = results['base_predictions']['lgbm']
xgb_preds = results['base_predictions']['xgb']  
catboost_preds = results['base_predictions']['catboost']
final_preds = results['final_predictions']

[I 2025-09-26 11:06:55,403] A new study created in memory with name: no-name-9d89d06f-dea8-4597-8a7a-afdc35c5b345

============================================================
HYPERPARAMETER TUNING PHASE
============================================================
Tuning LightGBM hyperparameters...

  0%|          | 0/100 [00:00<?, ?it/s]

Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[2]	valid_0's l2: 702.095
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[5]	valid_0's l2: 699.863
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[6]	valid_0's l2: 700.484
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[5]	valid_0's l2: 701.686
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[2]	valid_0's l2: 699.237
[I 2025-09-26 11:07:10,316] Trial 0 finished with value: 26.470220714282544 and parameters: {'n_estimators': 2498, 'learning_rate': 0.19063571821788408, 'num_leaves': 152, 'max_depth': 11, 'min_child_samples': 12, 'subsample': 0.662397808134481, 'colsample_bytree': 0.4348501673009197, 'reg_alpha': 1.7323522915498704, 'reg_lambda': 3.005575058716044}. Best is trial 0 with value: 26.470220714282544.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[72]	valid_0's l2: 701.805
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[127]	valid_0's l2: 699.623
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[109]	valid_0's l2: 700.302
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[108]	valid_0's l2: 701.295
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[159]	valid_0's l2: 698.987
[I 2025-09-26 11:07:51,339] Trial 1 finished with value: 26.46510770576375 and parameters: {'n_estimators': 3832, 'learning_rate': 0.013911053916202464, 'num_leaves': 195, 'max_depth': 14, 'min_child_samples': 14, 'subsample': 0.6727299868828402, 'colsample_bytree': 0.5100427059120604, 'reg_alpha': 0.6084844859190754, 'reg_lambda': 2.6237821581611893}. Best is trial 1 with value: 26.46510770576375.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[16]	valid_0's l2: 701.749
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[32]	valid_0's l2: 699.604
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[23]	valid_0's l2: 700.205
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[23]	valid_0's l2: 701.281
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 699.068
[I 2025-09-26 11:08:00,508] Trial 2 finished with value: 26.464712479462953 and parameters: {'n_estimators': 2728, 'learning_rate': 0.06533353663762796, 'num_leaves': 130, 'max_depth': 6, 'min_child_samples': 18, 'subsample': 0.7465447373174767, 'colsample_bytree': 0.6736419905302216, 'reg_alpha': 1.5703519227860272, 'reg_lambda': 0.9983689107917987}. Best is trial 2 with value: 26.464712479462953.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[9]	valid_0's l2: 701.66
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[12]	valid_0's l2: 699.622
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[11]	valid_0's l2: 700.133
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[10]	valid_0's l2: 701.34
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[13]	valid_0's l2: 699.018
[I 2025-09-26 11:08:07,128] Trial 3 finished with value: 26.464207366602597 and parameters: {'n_estimators': 3057, 'learning_rate': 0.12255876808378806, 'num_leaves': 28, 'max_depth': 11, 'min_child_samples': 12, 'subsample': 0.6260206371941118, 'colsample_bytree': 0.9693313223519999, 'reg_alpha': 1.9312640661491187, 'reg_lambda': 4.041986740582305}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[30]	valid_0's l2: 701.744
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[72]	valid_0's l2: 699.586
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[38]	valid_0's l2: 700.225
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[55]	valid_0's l2: 701.316
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[49]	valid_0's l2: 699.035
[I 2025-09-26 11:08:25,687] Trial 4 finished with value: 26.464707080432692 and parameters: {'n_estimators': 2218, 'learning_rate': 0.028557701661212936, 'num_leaves': 143, 'max_depth': 9, 'min_child_samples': 10, 'subsample': 0.798070764044508, 'colsample_bytree': 0.42063311266913106, 'reg_alpha': 1.8186408041575641, 'reg_lambda': 1.2938999080000846}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[10]	valid_0's l2: 701.823
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[19]	valid_0's l2: 699.638
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 700.295
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[17]	valid_0's l2: 701.334
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[13]	valid_0's l2: 698.974
[I 2025-09-26 11:08:38,382] Trial 5 finished with value: 26.46530508198623 and parameters: {'n_estimators': 3650, 'learning_rate': 0.06922510445698808, 'num_leaves': 114, 'max_depth': 11, 'min_child_samples': 13, 'subsample': 0.9878338511058234, 'colsample_bytree': 0.8650796940166687, 'reg_alpha': 1.8789978831283782, 'reg_lambda': 4.474136752138244}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[4]	valid_0's l2: 701.776
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[7]	valid_0's l2: 699.62
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[6]	valid_0's l2: 700.245
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[9]	valid_0's l2: 701.368
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[4]	valid_0's l2: 699.056
[I 2025-09-26 11:08:44,816] Trial 6 finished with value: 26.465307950141693 and parameters: {'n_estimators': 3392, 'learning_rate': 0.1851561046543922, 'num_leaves': 36, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.6332063738136893, 'reg_alpha': 0.5426980635477918, 'reg_lambda': 4.143687545759647}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[26]	valid_0's l2: 701.748
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[27]	valid_0's l2: 699.553
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[24]	valid_0's l2: 700.169
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[25]	valid_0's l2: 701.304
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[10]	valid_0's l2: 699.101
[I 2025-09-26 11:08:52,759] Trial 7 finished with value: 26.464592818604537 and parameters: {'n_estimators': 2427, 'learning_rate': 0.06337755684060234, 'num_leaves': 118, 'max_depth': 6, 'min_child_samples': 41, 'subsample': 0.6298202574719083, 'colsample_bytree': 0.9921321619603104, 'reg_alpha': 1.5444895385933148, 'reg_lambda': 0.993578407670862}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[4]	valid_0's l2: 701.861
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[5]	valid_0's l2: 699.802
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[3]	valid_0's l2: 700.418
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[3]	valid_0's l2: 701.495
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[3]	valid_0's l2: 699.078
[I 2025-09-26 11:09:03,949] Trial 8 finished with value: 26.467537519821043 and parameters: {'n_estimators': 1022, 'learning_rate': 0.1649376714064185, 'num_leaves': 147, 'max_depth': 13, 'min_child_samples': 40, 'subsample': 0.6296178606936361, 'colsample_bytree': 0.6150794371265635, 'reg_alpha': 0.23173811905025943, 'reg_lambda': 4.315517129377968}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[16]	valid_0's l2: 701.716
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[18]	valid_0's l2: 699.629
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[18]	valid_0's l2: 700.153
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[17]	valid_0's l2: 701.315
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 699.033
[I 2025-09-26 11:09:11,796] Trial 9 finished with value: 26.46448410664529 and parameters: {'n_estimators': 3493, 'learning_rate': 0.07287062472200334, 'num_leaves': 31, 'max_depth': 8, 'min_child_samples': 19, 'subsample': 0.8918424713352255, 'colsample_bytree': 0.7825344828131279, 'reg_alpha': 1.774425485152653, 'reg_lambda': 2.3610746258097466}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[9]	valid_0's l2: 701.798
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[12]	valid_0's l2: 699.702
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[9]	valid_0's l2: 700.265
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[7]	valid_0's l2: 701.265
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[4]	valid_0's l2: 699.054
[I 2025-09-26 11:09:21,187] Trial 10 finished with value: 26.4653857671186 and parameters: {'n_estimators': 4781, 'learning_rate': 0.13349025728684255, 'num_leaves': 66, 'max_depth': 15, 'min_child_samples': 28, 'subsample': 0.876098829427658, 'colsample_bytree': 0.9838501428924085, 'reg_alpha': 1.1998312736251522, 'reg_lambda': 3.2898109248551823}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[12]	valid_0's l2: 701.673
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[16]	valid_0's l2: 699.583
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[13]	valid_0's l2: 700.17
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[14]	valid_0's l2: 701.293
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[10]	valid_0's l2: 699.054
[I 2025-09-26 11:09:27,178] Trial 11 finished with value: 26.46420738084513 and parameters: {'n_estimators': 4379, 'learning_rate': 0.11075533298431563, 'num_leaves': 20, 'max_depth': 9, 'min_child_samples': 24, 'subsample': 0.8920339412764792, 'colsample_bytree': 0.8236248332447837, 'reg_alpha': 1.2143685480664512, 'reg_lambda': 2.202654840899742}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[9]	valid_0's l2: 701.831
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[11]	valid_0's l2: 699.608
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[10]	valid_0's l2: 700.279
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[8]	valid_0's l2: 701.407
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[5]	valid_0's l2: 699.059
[I 2025-09-26 11:09:35,542] Trial 12 finished with value: 26.465758594054517 and parameters: {'n_estimators': 4751, 'learning_rate': 0.11868889078782294, 'num_leaves': 70, 'max_depth': 10, 'min_child_samples': 28, 'subsample': 0.8945649978915543, 'colsample_bytree': 0.8640374585617869, 'reg_alpha': 1.1886892576018306, 'reg_lambda': 1.935723244580198}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[13]	valid_0's l2: 701.641
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[18]	valid_0's l2: 699.637
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[26]	valid_0's l2: 700.123
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[11]	valid_0's l2: 701.346
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[8]	valid_0's l2: 699.05
[I 2025-09-26 11:09:41,227] Trial 13 finished with value: 26.464301503731765 and parameters: {'n_estimators': 4241, 'learning_rate': 0.1433950033455413, 'num_leaves': 20, 'max_depth': 11, 'min_child_samples': 24, 'subsample': 0.9570230774646024, 'colsample_bytree': 0.8788937622546955, 'reg_alpha': 0.8500182386117703, 'reg_lambda': 3.552479272952497}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[6]	valid_0's l2: 701.782
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[18]	valid_0's l2: 699.678
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[11]	valid_0's l2: 700.296
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[10]	valid_0's l2: 701.331
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[11]	valid_0's l2: 698.978
[I 2025-09-26 11:09:49,079] Trial 14 finished with value: 26.46530775315252 and parameters: {'n_estimators': 1716, 'learning_rate': 0.10263929549773473, 'num_leaves': 63, 'max_depth': 13, 'min_child_samples': 34, 'subsample': 0.8126628978179207, 'colsample_bytree': 0.7739598811413334, 'reg_alpha': 1.3783116459697247, 'reg_lambda': 1.8153708788815472}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[10]	valid_0's l2: 701.759
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 699.674
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[12]	valid_0's l2: 700.183
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[14]	valid_0's l2: 701.317
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[8]	valid_0's l2: 699.049
[I 2025-09-26 11:09:56,514] Trial 15 finished with value: 26.46499121271259 and parameters: {'n_estimators': 4201, 'learning_rate': 0.11240424714492385, 'num_leaves': 49, 'max_depth': 9, 'min_child_samples': 21, 'subsample': 0.8245694381415021, 'colsample_bytree': 0.9297592501765279, 'reg_alpha': 1.997896966000035, 'reg_lambda': 4.886332327975389}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[7]	valid_0's l2: 701.857
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[17]	valid_0's l2: 699.59
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[15]	valid_0's l2: 700.351
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[10]	valid_0's l2: 701.412
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[7]	valid_0's l2: 699.066
[I 2025-09-26 11:10:06,340] Trial 16 finished with value: 26.466104756078163 and parameters: {'n_estimators': 3021, 'learning_rate': 0.09466758349380491, 'num_leaves': 96, 'max_depth': 12, 'min_child_samples': 5, 'subsample': 0.9364077019374849, 'colsample_bytree': 0.7817726812387205, 'reg_alpha': 0.9507021766696118, 'reg_lambda': 0.06589607190461777}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[4]	valid_0's l2: 701.836
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[7]	valid_0's l2: 699.73
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[8]	valid_0's l2: 700.294
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[5]	valid_0's l2: 701.418
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[3]	valid_0's l2: 699.129
[I 2025-09-26 11:10:15,757] Trial 17 finished with value: 26.466600014606758 and parameters: {'n_estimators': 1853, 'learning_rate': 0.14913248528001563, 'num_leaves': 97, 'max_depth': 8, 'min_child_samples': 33, 'subsample': 0.7358972889765202, 'colsample_bytree': 0.9330702343512591, 'reg_alpha': 0.07260962646423674, 'reg_lambda': 3.960543567886938}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[9]	valid_0's l2: 701.707
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[11]	valid_0's l2: 699.598
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[9]	valid_0's l2: 700.195
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[13]	valid_0's l2: 701.405
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[4]	valid_0's l2: 699.097
[I 2025-09-26 11:10:22,785] Trial 18 finished with value: 26.46506820657901 and parameters: {'n_estimators': 4994, 'learning_rate': 0.1662783226668982, 'num_leaves': 49, 'max_depth': 5, 'min_child_samples': 33, 'subsample': 0.8456552068092515, 'colsample_bytree': 0.7383848194128597, 'reg_alpha': 1.3211673680363565, 'reg_lambda': 2.787098183977799}. Best is trial 3 with value: 26.464207366602597.
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[7]	valid_0's l2: 701.942
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[12]	valid_0's l2: 699.664
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[6]	valid_0's l2: 700.292
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[8]	valid_0's l2: 701.475
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[7]	valid_0's l2: 699.053

[I 2025-09-26 11:21:58,642] A new study created in memory with name: no-name-feadaa12-ea69-4c91-af0f-34dd2257126f

Early stopping, best iteration is:
[35]	valid_0's l2: 699.005
[I 2025-09-26 11:21:58,638] Trial 99 finished with value: 26.463603468353092 and parameters: {'n_estimators': 3606, 'learning_rate': 0.050298670227575976, 'num_leaves': 33, 'max_depth': 15, 'min_child_samples': 16, 'subsample': 0.6854161459868355, 'colsample_bytree': 0.6532904538975192, 'reg_alpha': 1.3449266313911674, 'reg_lambda': 2.0994974451955306}. Best is trial 64 with value: 26.46340974432102.
Best LightGBM RMSE: 26.4634
Best LightGBM params: {'n_estimators': 3128, 'learning_rate': 0.07606034036075258, 'num_leaves': 32, 'max_depth': 15, 'min_child_samples': 11, 'subsample': 0.7695038018665359, 'colsample_bytree': 0.9148924908988627, 'reg_alpha': 0.3053687313839587, 'reg_lambda': 3.141052432792816}

Tuning XGBoost hyperparameters...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-09-26 11:22:12,208] Trial 0 finished with value: 26.479240173722644 and parameters: {'n_estimators': 2498, 'learning_rate': 0.19063571821788408, 'max_depth': 13, 'min_child_weight': 12, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.49359671220172163, 'reg_alpha': 0.11616722433639892, 'reg_lambda': 4.330880728874676}. Best is trial 0 with value: 26.479240173722644.
[I 2025-09-26 11:22:16,000] Trial 1 finished with value: 26.466922048158807 and parameters: {'n_estimators': 3405, 'learning_rate': 0.14453378978124864, 'max_depth': 5, 'min_child_weight': 20, 'subsample': 0.9329770563201687, 'colsample_bytree': 0.5274034664069657, 'reg_alpha': 0.36364993441420124, 'reg_lambda': 0.9170225492671691}. Best is trial 1 with value: 26.466922048158807.
[I 2025-09-26 11:22:21,799] Trial 2 finished with value: 26.47174044253789 and parameters: {'n_estimators': 2217, 'learning_rate': 0.10970372201012518, 'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.8447411578889518, 'colsample_bytree': 0.4836963163912251, 'reg_alpha': 0.5842892970704363, 'reg_lambda': 1.8318092164684585}. Best is trial 1 with value: 26.466922048158807.
[I 2025-09-26 11:22:26,067] Trial 3 finished with value: 26.468634917129116 and parameters: {'n_estimators': 2824, 'learning_rate': 0.1591834326646726, 'max_depth': 7, 'min_child_weight': 11, 'subsample': 0.836965827544817, 'colsample_bytree': 0.42787024763199866, 'reg_alpha': 1.2150897038028767, 'reg_lambda': 0.8526206184364576}. Best is trial 1 with value: 26.466922048158807.
[I 2025-09-26 11:22:43,592] Trial 4 finished with value: 26.48561128996696 and parameters: {'n_estimators': 1260, 'learning_rate': 0.19028825207813332, 'max_depth': 15, 'min_child_weight': 17, 'subsample': 0.7218455076693483, 'colsample_bytree': 0.45860326840383037, 'reg_alpha': 1.3684660530243138, 'reg_lambda': 2.2007624686980067}. Best is trial 1 with value: 26.466922048158807.
[I 2025-09-26 11:22:47,543] Trial 5 finished with value: 26.46615527260048 and parameters: {'n_estimators': 1488, 'learning_rate': 0.10408361292114134, 'max_depth': 5, 'min_child_weight': 19, 'subsample': 0.7035119926400067, 'colsample_bytree': 0.7975133706123891, 'reg_alpha': 0.6234221521788219, 'reg_lambda': 2.600340105889054}. Best is trial 5 with value: 26.46615527260048.
[I 2025-09-26 11:23:09,349] Trial 6 finished with value: 26.47185387152187 and parameters: {'n_estimators': 3187, 'learning_rate': 0.04512234654985014, 'max_depth': 15, 'min_child_weight': 16, 'subsample': 0.9757995766256756, 'colsample_bytree': 0.9368964102565893, 'reg_alpha': 1.1957999576221703, 'reg_lambda': 4.609371175115584}. Best is trial 5 with value: 26.46615527260048.
[I 2025-09-26 11:23:13,795] Trial 7 finished with value: 26.465523444132764 and parameters: {'n_estimators': 1354, 'learning_rate': 0.04723674385963759, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.7554709158757928, 'colsample_bytree': 0.5628094190643376, 'reg_alpha': 1.6574750183038587, 'reg_lambda': 1.7837666334679465}. Best is trial 7 with value: 26.465523444132764.
[I 2025-09-26 11:23:18,014] Trial 8 finished with value: 26.46751089930414 and parameters: {'n_estimators': 2124, 'learning_rate': 0.1131122558000672, 'max_depth': 6, 'min_child_weight': 17, 'subsample': 0.6298202574719083, 'colsample_bytree': 0.9921321619603104, 'reg_alpha': 1.5444895385933148, 'reg_lambda': 0.993578407670862}. Best is trial 7 with value: 26.465523444132764.
[I 2025-09-26 11:23:27,606] Trial 9 finished with value: 26.47585199766663 and parameters: {'n_estimators': 1022, 'learning_rate': 0.1649376714064185, 'max_depth': 12, 'min_child_weight': 15, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.44442679104045424, 'reg_alpha': 0.7169314570885452, 'reg_lambda': 0.5793452976256486}. Best is trial 7 with value: 26.465523444132764.
[I 2025-09-26 11:23:40,651] Trial 10 finished with value: 26.466501556420347 and parameters: {'n_estimators': 4781, 'learning_rate': 0.011139464761605267, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.768161603273759, 'colsample_bytree': 0.6281757761510864, 'reg_alpha': 1.9418734303410015, 'reg_lambda': 3.3828618987138985}. Best is trial 7 with value: 26.465523444132764.
[I 2025-09-26 11:23:45,452] Trial 11 finished with value: 26.467403396355632 and parameters: {'n_estimators': 1722, 'learning_rate': 0.06813250046536201, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.7143417233780396, 'colsample_bytree': 0.8112771130272837, 'reg_alpha': 0.8608274236786436, 'reg_lambda': 3.0976697156679958}. Best is trial 7 with value: 26.465523444132764.
[I 2025-09-26 11:23:49,631] Trial 12 finished with value: 26.465929044478845 and parameters: {'n_estimators': 1640, 'learning_rate': 0.07292183078003155, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.7670719489688085, 'colsample_bytree': 0.7166673358180191, 'reg_alpha': 1.9885004644875481, 'reg_lambda': 1.7669806916348032}. Best is trial 7 with value: 26.465523444132764.
[I 2025-09-26 11:23:55,229] Trial 13 finished with value: 26.467045393993413 and parameters: {'n_estimators': 3805, 'learning_rate': 0.06401755669996026, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.8056891692692755, 'colsample_bytree': 0.6459794421977856, 'reg_alpha': 1.9987248772831023, 'reg_lambda': 1.842222549202605}. Best is trial 7 with value: 26.465523444132764.
[I 2025-09-26 11:24:00,359] Trial 14 finished with value: 26.465516672661032 and parameters: {'n_estimators': 1898, 'learning_rate': 0.029416430691092305, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.7688977176118464, 'colsample_bytree': 0.5871269641392607, 'reg_alpha': 1.6721813817045639, 'reg_lambda': 0.03987609977138584}. Best is trial 14 with value: 26.465516672661032.
[I 2025-09-26 11:24:17,616] Trial 15 finished with value: 26.467622107901228 and parameters: {'n_estimators': 1957, 'learning_rate': 0.015231511285697628, 'max_depth': 11, 'min_child_weight': 2, 'subsample': 0.8637174471935178, 'colsample_bytree': 0.575789974863184, 'reg_alpha': 1.607287919460977, 'reg_lambda': 0.01698467938803034}. Best is trial 14 with value: 26.465516672661032.
[I 2025-09-26 11:24:24,747] Trial 16 finished with value: 26.466573832502313 and parameters: {'n_estimators': 2619, 'learning_rate': 0.03848533688297373, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.6062041527976909, 'colsample_bytree': 0.7155436575313667, 'reg_alpha': 1.6469149816663904, 'reg_lambda': 0.0860690651043472}. Best is trial 14 with value: 26.465516672661032.
[I 2025-09-26 11:24:34,433] Trial 17 finished with value: 26.47007931833856 and parameters: {'n_estimators': 1004, 'learning_rate': 0.03817822089969851, 'max_depth': 10, 'min_child_weight': 4, 'subsample': 0.7673758708920512, 'colsample_bytree': 0.5688485557473757, 'reg_alpha': 1.7532604875403603, 'reg_lambda': 3.68986738161129}. Best is trial 14 with value: 26.465516672661032.
[I 2025-09-26 11:24:38,657] Trial 18 finished with value: 26.468010078863905 and parameters: {'n_estimators': 4483, 'learning_rate': 0.09178589575168604, 'max_depth': 6, 'min_child_weight': 9, 'subsample': 0.6879583627725717, 'colsample_bytree': 0.6579796035011403, 'reg_alpha': 1.1473789350111838, 'reg_lambda': 1.4669827146002723}. Best is trial 14 with value: 26.465516672661032.
[I 2025-09-26 11:24:46,947] Trial 19 finished with value: 26.46616541366627 and parameters: {'n_estimators': 3920, 'learning_rate': 0.02772512991622121, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7890087942297312, 'colsample_bytree': 0.7899465799434123, 'reg_alpha': 1.4510859327244288, 'reg_lambda': 2.414243232306961}. Best is trial 14 with value: 26.465516672661032.
[I 2025-09-26 11:24:51,621] Trial 20 finished with value: 26.466171105423655 and parameters: {'n_estimators': 2315, 'learning_rate': 0.061668180506208495, 'max_depth': 6, 'min_child_weight': 13, 'subsample': 0.8781659231750595, 'colsample_bytree': 0.5817133886507502, 'reg_alpha': 0.9426484195559957, 'reg_lambda': 1.3590259376687215}. Best is trial 14 with value: 26.465516672661032.
[I 2025-09-26 11:24:55,737] Trial 21 finished with value: 26.466307160435925 and parameters: {'n_estimators': 1659, 'learning_rate': 0.08319829949039574, 'max_depth': 5, 'min_child_weight': 9, 'subsample': 0.7494838667294444, 'colsample_bytree': 0.719991625156796, 'reg_alpha': 1.820313458887435, 'reg_lambda': 1.5937129799807837}. Best is trial 14 with value: 26.465516672661032.
[I 2025-09-26 11:25:00,237] Trial 22 finished with value: 26.465752188782545 and parameters: {'n_estimators': 1446, 'learning_rate': 0.05141242109416311, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.8230405426861238, 'colsample_bytree': 0.7582268050236641, 'reg_alpha': 1.7483032816842379, 'reg_lambda': 2.819012144141641}. Best is trial 14 with value: 26.465516672661032.
[I 2025-09-26 11:25:05,135] Trial 23 finished with value: 26.46519039632769 and parameters: {'n_estimators': 1931, 'learning_rate': 0.048896771126198675, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.8251362836201439, 'colsample_bytree': 0.862938171774362, 'reg_alpha': 1.3690652969443229, 'reg_lambda': 2.8979992122967646}. Best is trial 23 with value: 26.46519039632769.
[I 2025-09-26 11:25:11,182] Trial 24 finished with value: 26.465284373749547 and parameters: {'n_estimators': 1940, 'learning_rate': 0.02554066746125021, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.7442578096512015, 'colsample_bytree': 0.8366425322027263, 'reg_alpha': 1.3684909874296445, 'reg_lambda': 3.863873027758985}. Best is trial 23 with value: 26.46519039632769.
[I 2025-09-26 11:25:18,413] Trial 25 finished with value: 26.46623982423015 and parameters: {'n_estimators': 1924, 'learning_rate': 0.02369256589489821, 'max_depth': 8, 'min_child_weight': 5, 'subsample': 0.8012364486139857, 'colsample_bytree': 0.8542109190944076, 'reg_alpha': 1.3821426328551722, 'reg_lambda': 3.698823382679046}. Best is trial 23 with value: 26.46519039632769.
[I 2025-09-26 11:25:24,434] Trial 26 finished with value: 26.465236686863353 and parameters: {'n_estimators': 2684, 'learning_rate': 0.023396542167836376, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6687840829785424, 'colsample_bytree': 0.9027813175948978, 'reg_alpha': 1.0990575402967244, 'reg_lambda': 4.967604215082753}. Best is trial 23 with value: 26.46519039632769.
[I 2025-09-26 11:25:31,755] Trial 27 finished with value: 26.465939854013662 and parameters: {'n_estimators': 2945, 'learning_rate': 0.01673465002247928, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6538322751760228, 'colsample_bytree': 0.9111083261987523, 'reg_alpha': 1.0520064301224927, 'reg_lambda': 4.915098024679516}. Best is trial 23 with value: 26.46519039632769.
[I 2025-09-26 11:25:38,859] Trial 28 finished with value: 26.468282910978456 and parameters: {'n_estimators': 2590, 'learning_rate': 0.05125252560221949, 'max_depth': 9, 'min_child_weight': 4, 'subsample': 0.6746024429751704, 'colsample_bytree': 0.8714994019034032, 'reg_alpha': 1.2849331099802628, 'reg_lambda': 4.269640009380537}. Best is trial 23 with value: 26.46519039632769.
[I 2025-09-26 11:25:43,294] Trial 29 finished with value: 26.467161672777895 and parameters: {'n_estimators': 2431, 'learning_rate': 0.12403013579720852, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6491486846425747, 'colsample_bytree': 0.9754814660636715, 'reg_alpha': 1.075425861003027, 'reg_lambda': 4.165713630600516}. Best is trial 23 with value: 26.46519039632769.
[I 2025-09-26 11:25:57,525] Trial 30 finished with value: 26.473152709454318 and parameters: {'n_estimators': 2715, 'learning_rate': 0.08061534210620766, 'max_depth': 13, 'min_child_weight': 13, 'subsample': 0.7308743428154476, 'colsample_bytree': 0.8767424573901128, 'reg_alpha': 0.08549036015928346, 'reg_lambda': 3.9559948666763014}. Best is trial 23 with value: 26.46519039632769.
[I 2025-09-26 11:26:02,939] Trial 31 finished with value: 26.465021985845226 and parameters: {'n_estimators': 1965, 'learning_rate': 0.0307801100677334, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.7892089461038542, 'colsample_bytree': 0.9278947965548229, 'reg_alpha': 1.4429693259381364, 'reg_lambda': 4.945047189521876}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:26:08,273] Trial 32 finished with value: 26.465220450191033 and parameters: {'n_estimators': 3306, 'learning_rate': 0.03289302442991803, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.6899963636399518, 'colsample_bytree': 0.9356887978887635, 'reg_alpha': 1.499105249232499, 'reg_lambda': 4.992246641067313}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:26:13,753] Trial 33 finished with value: 26.46651743033591 and parameters: {'n_estimators': 3286, 'learning_rate': 0.03559716418971802, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6175556629591956, 'colsample_bytree': 0.9275094010926053, 'reg_alpha': 1.4690808994375963, 'reg_lambda': 4.941440707563995}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:26:19,499] Trial 34 finished with value: 26.468176551560276 and parameters: {'n_estimators': 3527, 'learning_rate': 0.05879246768428422, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6937687526041839, 'colsample_bytree': 0.9471104283544702, 'reg_alpha': 0.3060359539352938, 'reg_lambda': 4.69716624477172}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:26:26,426] Trial 35 finished with value: 26.465381158741838 and parameters: {'n_estimators': 3108, 'learning_rate': 0.013165078988003787, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8889178295307477, 'colsample_bytree': 0.9087746243745491, 'reg_alpha': 1.2840095153370499, 'reg_lambda': 4.524903839410072}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:26:36,915] Trial 36 finished with value: 26.46912386269891 and parameters: {'n_estimators': 3553, 'learning_rate': 0.03756885474794934, 'max_depth': 10, 'min_child_weight': 1, 'subsample': 0.8454913226640355, 'colsample_bytree': 0.9608950142126784, 'reg_alpha': 0.827145827942789, 'reg_lambda': 4.4090892015664425}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:26:41,170] Trial 37 finished with value: 26.469511250767464 and parameters: {'n_estimators': 2183, 'learning_rate': 0.19871535041343594, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.9622383611178279, 'colsample_bytree': 0.9041020801524967, 'reg_alpha': 1.5479448843873458, 'reg_lambda': 4.740051728315971}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:26:45,700] Trial 38 finished with value: 26.46587354949877 and parameters: {'n_estimators': 2789, 'learning_rate': 0.05257466912273508, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.6384676277045094, 'colsample_bytree': 0.8854208787801862, 'reg_alpha': 1.2588828021283425, 'reg_lambda': 4.162568234878229}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:26:54,882] Trial 39 finished with value: 26.467164183377612 and parameters: {'n_estimators': 4016, 'learning_rate': 0.023336729298832112, 'max_depth': 9, 'min_child_weight': 2, 'subsample': 0.6700132390605775, 'colsample_bytree': 0.8285396612915561, 'reg_alpha': 1.1651821517153813, 'reg_lambda': 4.995558335209031}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:27:13,333] Trial 40 finished with value: 26.475624304794394 and parameters: {'n_estimators': 3025, 'learning_rate': 0.09602744257931398, 'max_depth': 14, 'min_child_weight': 11, 'subsample': 0.8257321055916308, 'colsample_bytree': 0.9984500793949384, 'reg_alpha': 0.9775982833131391, 'reg_lambda': 3.4032349520663074}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:27:18,510] Trial 41 finished with value: 26.465710444091922 and parameters: {'n_estimators': 2426, 'learning_rate': 0.028954724594884858, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.7226654328509374, 'colsample_bytree': 0.8391569619601955, 'reg_alpha': 1.399780347652725, 'reg_lambda': 4.044617400253471}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:27:23,645] Trial 42 finished with value: 26.46666597312432 and parameters: {'n_estimators': 2068, 'learning_rate': 0.044022885779816064, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.7390726102016156, 'colsample_bytree': 0.7635167701826462, 'reg_alpha': 1.3219526918801898, 'reg_lambda': 3.8154659578191135}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:27:29,637] Trial 43 finished with value: 26.46556373631492 and parameters: {'n_estimators': 1237, 'learning_rate': 0.021191066893852365, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7073777619505893, 'colsample_bytree': 0.9457241631999472, 'reg_alpha': 1.4975155353884773, 'reg_lambda': 4.480014992643165}. Best is trial 31 with value: 26.465021985845226.
[I 2025-09-26 11:27:37,603] Trial 44 finished with value: 26.464969008912828 and parameters: {'n_estimators': 1759, 'learning_rate': 0.010226315675221738, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6821048544304472, 'colsample_bytree': 0.8462502333580982, 'reg_alpha': 1.1696133920656202, 'reg_lambda': 3.350330521206737}. Best is trial 44 with value: 26.464969008912828.
[I 2025-09-26 11:27:42,586] Trial 45 finished with value: 26.464966550059984 and parameters: {'n_estimators': 1772, 'learning_rate': 0.03259512389101908, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6845961752832307, 'colsample_bytree': 0.8607497808664172, 'reg_alpha': 1.103607459673809, 'reg_lambda': 2.994295227061194}. Best is trial 45 with value: 26.464966550059984.
[I 2025-09-26 11:27:46,351] Trial 46 finished with value: 26.4668628156539 and parameters: {'n_estimators': 1705, 'learning_rate': 0.14850705901136485, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.689420904546801, 'colsample_bytree': 0.8652115871143627, 'reg_alpha': 1.2051587889850828, 'reg_lambda': 2.918561003013226}. Best is trial 45 with value: 26.464966550059984.
[I 2025-09-26 11:27:54,361] Trial 47 finished with value: 26.465052144261694 and parameters: {'n_estimators': 1236, 'learning_rate': 0.010346493794075682, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.8561160384747982, 'colsample_bytree': 0.792808118446317, 'reg_alpha': 0.7066575596339191, 'reg_lambda': 2.3413625873929087}. Best is trial 45 with value: 26.464966550059984.
[I 2025-09-26 11:28:02,462] Trial 48 finished with value: 26.46507363617045 and parameters: {'n_estimators': 1245, 'learning_rate': 0.010764659539719224, 'max_depth': 5, 'min_child_weight': 19, 'subsample': 0.85374414118242, 'colsample_bytree': 0.7727732374122405, 'reg_alpha': 0.6084347863917057, 'reg_lambda': 2.347476564985388}. Best is trial 45 with value: 26.464966550059984.
[I 2025-09-26 11:28:09,756] Trial 49 finished with value: 26.46526595740096 and parameters: {'n_estimators': 1191, 'learning_rate': 0.011958798897283969, 'max_depth': 5, 'min_child_weight': 20, 'subsample': 0.9047196124654876, 'colsample_bytree': 0.7794213011271405, 'reg_alpha': 0.3987677616522006, 'reg_lambda': 2.1579087056882846}. Best is trial 45 with value: 26.464966550059984.
[I 2025-09-26 11:28:17,245] Trial 50 finished with value: 26.465158357648317 and parameters: {'n_estimators': 1491, 'learning_rate': 0.010797384167318578, 'max_depth': 5, 'min_child_weight': 16, 'subsample': 0.8449993522431064, 'colsample_bytree': 0.746389179423709, 'reg_alpha': 0.5451646264850016, 'reg_lambda': 2.154897245662583}. Best is trial 45 with value: 26.464966550059984.
[I 2025-09-26 11:28:24,286] Trial 51 finished with value: 26.465009922963485 and parameters: {'n_estimators': 1489, 'learning_rate': 0.011947232232078409, 'max_depth': 5, 'min_child_weight': 18, 'subsample': 0.8592617929265639, 'colsample_bytree': 0.7966734467433441, 'reg_alpha': 0.550394300474679, 'reg_lambda': 2.1859099549828485}. Best is trial 45 with value: 26.464966550059984.

[I 2025-09-26 11:34:36,382] A new study created in memory with name: no-name-25704ed6-657a-47dc-b9f6-c0008b1ef58c

[I 2025-09-26 11:34:36,378] Trial 99 finished with value: 26.46678573216236 and parameters: {'n_estimators': 2045, 'learning_rate': 0.03557242711342376, 'max_depth': 8, 'min_child_weight': 6, 'subsample': 0.743219043539105, 'colsample_bytree': 0.709545969070398, 'reg_alpha': 1.2380319850948849, 'reg_lambda': 0.7833656337060014}. Best is trial 45 with value: 26.464966550059984.
Best XGBoost RMSE: 26.4650
Best XGBoost params: {'n_estimators': 1772, 'learning_rate': 0.03259512389101908, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.6845961752832307, 'colsample_bytree': 0.8607497808664172, 'reg_alpha': 1.103607459673809, 'reg_lambda': 2.994295227061194}

Tuning CatBoost hyperparameters...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-09-26 11:34:41,463] Trial 0 finished with value: 26.46752299943156 and parameters: {'iterations': 2123, 'learning_rate': 0.19063571821788408, 'depth': 9, 'min_data_in_leaf': 32, 'subsample': 0.6624074561769746, 'random_strength': 0.8899863008405067, 'reg_lambda': 0.2904180608409973}. Best is trial 0 with value: 26.46752299943156.
[I 2025-09-26 11:34:46,192] Trial 1 finished with value: 26.465673684200897 and parameters: {'iterations': 3599, 'learning_rate': 0.12421185223120967, 'depth': 8, 'min_data_in_leaf': 5, 'subsample': 0.9879639408647978, 'random_strength': 2.5811066020010545, 'reg_lambda': 1.0616955533913808}. Best is trial 1 with value: 26.465673684200897.
[I 2025-09-26 11:34:51,779] Trial 2 finished with value: 26.46445542770964 and parameters: {'iterations': 1545, 'learning_rate': 0.044846856872152424, 'depth': 6, 'min_data_in_leaf': 29, 'subsample': 0.7727780074568463, 'random_strength': 1.2280728504951048, 'reg_lambda': 3.0592644736118975}. Best is trial 2 with value: 26.46445542770964.
[I 2025-09-26 11:34:56,997] Trial 3 finished with value: 26.464596564292957 and parameters: {'iterations': 1418, 'learning_rate': 0.06550748322169145, 'depth': 6, 'min_data_in_leaf': 25, 'subsample': 0.9140703845572055, 'random_strength': 0.9991844553958993, 'reg_lambda': 2.571172192068058}. Best is trial 2 with value: 26.46445542770964.
[I 2025-09-26 11:35:05,561] Trial 4 finished with value: 26.46448805838 and parameters: {'iterations': 2777, 'learning_rate': 0.01882557841679957, 'depth': 8, 'min_data_in_leaf': 12, 'subsample': 0.6260206371941118, 'random_strength': 2.8722138431333333, 'reg_lambda': 4.828160165372797}. Best is trial 2 with value: 26.46445542770964.
[I 2025-09-26 11:35:10,875] Trial 5 finished with value: 26.464689174717005 and parameters: {'iterations': 3426, 'learning_rate': 0.06787661614294042, 'depth': 4, 'min_data_in_leaf': 36, 'subsample': 0.7760609974958406, 'random_strength': 0.8050955871119471, 'reg_lambda': 2.475884550556351}. Best is trial 2 with value: 26.46445542770964.
[I 2025-09-26 11:35:15,299] Trial 6 finished with value: 26.464316913377182 and parameters: {'iterations': 1103, 'learning_rate': 0.1827708763949686, 'depth': 5, 'min_data_in_leaf': 35, 'subsample': 0.7246844304357644, 'random_strength': 1.800170052944527, 'reg_lambda': 2.7335513967163982}. Best is trial 6 with value: 26.464316913377182.
[I 2025-09-26 11:35:20,637] Trial 7 finished with value: 26.466601134955532 and parameters: {'iterations': 1554, 'learning_rate': 0.19422107927526613, 'depth': 9, 'min_data_in_leaf': 48, 'subsample': 0.9579309401710595, 'random_strength': 1.9947499470277128, 'reg_lambda': 4.609371175115584}. Best is trial 6 with value: 26.464316913377182.
[I 2025-09-26 11:35:26,735] Trial 8 finished with value: 26.464795821421973 and parameters: {'iterations': 1265, 'learning_rate': 0.04723674385963759, 'depth': 4, 'min_data_in_leaf': 19, 'subsample': 0.7554709158757928, 'random_strength': 1.1783725794347397, 'reg_lambda': 4.143687545759647}. Best is trial 6 with value: 26.464316913377182.
[I 2025-09-26 11:35:32,043] Trial 9 finished with value: 26.464949230050543 and parameters: {'iterations': 2070, 'learning_rate': 0.06337755684060234, 'depth': 7, 'min_data_in_leaf': 11, 'subsample': 0.9208787923016158, 'random_strength': 0.686376609199427, 'reg_lambda': 4.9344346830025865}. Best is trial 6 with value: 26.464316913377182.
[I 2025-09-26 11:35:36,744] Trial 10 finished with value: 26.464872579424537 and parameters: {'iterations': 2541, 'learning_rate': 0.14416539387158867, 'depth': 5, 'min_data_in_leaf': 42, 'subsample': 0.7090747508804338, 'random_strength': 1.8523597704388697, 'reg_lambda': 1.806559982209047}. Best is trial 6 with value: 26.464316913377182.
[I 2025-09-26 11:35:41,147] Trial 11 finished with value: 26.464727253516344 and parameters: {'iterations': 1036, 'learning_rate': 0.15148557089563977, 'depth': 6, 'min_data_in_leaf': 26, 'subsample': 0.8462948165495066, 'random_strength': 1.4411489983969523, 'reg_lambda': 3.4069186840504098}. Best is trial 6 with value: 26.464316913377182.
[I 2025-09-26 11:35:46,221] Trial 12 finished with value: 26.46470333055089 and parameters: {'iterations': 1799, 'learning_rate': 0.10411444492502218, 'depth': 6, 'min_data_in_leaf': 38, 'subsample': 0.832734848163876, 'random_strength': 2.118006149921168, 'reg_lambda': 3.2650158007210663}. Best is trial 6 with value: 26.464316913377182.
[I 2025-09-26 11:35:51,422] Trial 13 finished with value: 26.46408516706332 and parameters: {'iterations': 1022, 'learning_rate': 0.09905399158869002, 'depth': 5, 'min_data_in_leaf': 29, 'subsample': 0.7081962459060129, 'random_strength': 1.4915613991138674, 'reg_lambda': 3.3693207447025104}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:35:56,005] Trial 14 finished with value: 26.46456181866397 and parameters: {'iterations': 2953, 'learning_rate': 0.09859967915666788, 'depth': 5, 'min_data_in_leaf': 21, 'subsample': 0.7019929089299466, 'random_strength': 1.5780775016286896, 'reg_lambda': 3.989974345395084}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:00,170] Trial 15 finished with value: 26.464412310003958 and parameters: {'iterations': 1055, 'learning_rate': 0.1748397337571589, 'depth': 5, 'min_data_in_leaf': 44, 'subsample': 0.6019992989734795, 'random_strength': 2.4116482043857186, 'reg_lambda': 1.9416078873503846}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:04,528] Trial 16 finished with value: 26.464421952474446 and parameters: {'iterations': 1968, 'learning_rate': 0.1296126719881726, 'depth': 4, 'min_data_in_leaf': 33, 'subsample': 0.730269603264092, 'random_strength': 1.6363968404054552, 'reg_lambda': 3.7569610233258426}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:10,914] Trial 17 finished with value: 26.46704476461875 and parameters: {'iterations': 2346, 'learning_rate': 0.08674027697583483, 'depth': 10, 'min_data_in_leaf': 50, 'subsample': 0.6652254504883938, 'random_strength': 2.2611930941467926, 'reg_lambda': 2.669266024657808}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:15,534] Trial 18 finished with value: 26.465342038983415 and parameters: {'iterations': 1001, 'learning_rate': 0.1618173507858578, 'depth': 7, 'min_data_in_leaf': 39, 'subsample': 0.8199399213734675, 'random_strength': 1.3538752373387308, 'reg_lambda': 1.7919514239527095}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:19,812] Trial 19 finished with value: 26.464985211749017 and parameters: {'iterations': 1731, 'learning_rate': 0.12544557496678235, 'depth': 5, 'min_data_in_leaf': 20, 'subsample': 0.6693345986529813, 'random_strength': 1.850237550283984, 'reg_lambda': 1.1142562304519625}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:24,437] Trial 20 finished with value: 26.464546753336823 and parameters: {'iterations': 3984, 'learning_rate': 0.08528071045181117, 'depth': 7, 'min_data_in_leaf': 33, 'subsample': 0.8793934770393718, 'random_strength': 0.5083802241801227, 'reg_lambda': 3.0207927475059955}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:28,565] Trial 21 finished with value: 26.46453764967236 and parameters: {'iterations': 1294, 'learning_rate': 0.17479711269465395, 'depth': 5, 'min_data_in_leaf': 44, 'subsample': 0.6008617364973166, 'random_strength': 2.4485705057791964, 'reg_lambda': 2.0048311882612477}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:32,955] Trial 22 finished with value: 26.464562979148177 and parameters: {'iterations': 1129, 'learning_rate': 0.17649120059916942, 'depth': 5, 'min_data_in_leaf': 45, 'subsample': 0.6219890565703622, 'random_strength': 2.943674305345517, 'reg_lambda': 2.190030403486892}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:36,801] Trial 23 finished with value: 26.464869843340733 and parameters: {'iterations': 1416, 'learning_rate': 0.19928282303699663, 'depth': 4, 'min_data_in_leaf': 38, 'subsample': 0.7314745188984569, 'random_strength': 2.562129727808336, 'reg_lambda': 1.323086093371383}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:40,936] Trial 24 finished with value: 26.464381349442544 and parameters: {'iterations': 1719, 'learning_rate': 0.17511368426412238, 'depth': 5, 'min_data_in_leaf': 42, 'subsample': 0.6927754051252023, 'random_strength': 2.2507195831244857, 'reg_lambda': 3.5936976664612414}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:45,917] Trial 25 finished with value: 26.464698838120523 and parameters: {'iterations': 1778, 'learning_rate': 0.1486989343353341, 'depth': 6, 'min_data_in_leaf': 28, 'subsample': 0.6905448483290493, 'random_strength': 2.102060784526116, 'reg_lambda': 3.5820068954774076}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:50,338] Trial 26 finished with value: 26.464641077856573 and parameters: {'iterations': 1604, 'learning_rate': 0.1176283910147562, 'depth': 4, 'min_data_in_leaf': 35, 'subsample': 0.7972510943744766, 'random_strength': 1.7282922679931496, 'reg_lambda': 4.447782097330527}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:54,377] Trial 27 finished with value: 26.464733216118873 and parameters: {'iterations': 1306, 'learning_rate': 0.16646530347523741, 'depth': 5, 'min_data_in_leaf': 41, 'subsample': 0.7402345097480125, 'random_strength': 1.4876229873003133, 'reg_lambda': 2.9556888423962553}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:36:58,748] Trial 28 finished with value: 26.464781884712853 and parameters: {'iterations': 2284, 'learning_rate': 0.13891122214706772, 'depth': 6, 'min_data_in_leaf': 30, 'subsample': 0.6494417913205516, 'random_strength': 2.2439050596938297, 'reg_lambda': 3.726099810920756}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:03,112] Trial 29 finished with value: 26.46454839515551 and parameters: {'iterations': 1891, 'learning_rate': 0.18472462897744457, 'depth': 4, 'min_data_in_leaf': 31, 'subsample': 0.6924216463265762, 'random_strength': 1.923593525198244, 'reg_lambda': 4.24846322558455}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:07,865] Trial 30 finished with value: 26.465775319779247 and parameters: {'iterations': 1226, 'learning_rate': 0.15555931829752687, 'depth': 8, 'min_data_in_leaf': 22, 'subsample': 0.6538272058884239, 'random_strength': 1.0283659147894308, 'reg_lambda': 0.11002168481556573}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:12,714] Trial 31 finished with value: 26.46437200209172 and parameters: {'iterations': 1006, 'learning_rate': 0.18347513943150748, 'depth': 5, 'min_data_in_leaf': 47, 'subsample': 0.6318984379839749, 'random_strength': 2.401275745029121, 'reg_lambda': 2.325151320483699}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:17,122] Trial 32 finished with value: 26.46474226791952 and parameters: {'iterations': 1425, 'learning_rate': 0.19008469878658713, 'depth': 5, 'min_data_in_leaf': 47, 'subsample': 0.6378138804056598, 'random_strength': 2.3031059837875327, 'reg_lambda': 2.756684546604314}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:21,654] Trial 33 finished with value: 26.465423104134203 and parameters: {'iterations': 1182, 'learning_rate': 0.1633073393273261, 'depth': 6, 'min_data_in_leaf': 41, 'subsample': 0.6763784017496733, 'random_strength': 2.7470790186538947, 'reg_lambda': 0.534439092633042}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:26,117] Trial 34 finished with value: 26.46483410414794 and parameters: {'iterations': 1604, 'learning_rate': 0.11518586775378632, 'depth': 5, 'min_data_in_leaf': 35, 'subsample': 0.711151954314865, 'random_strength': 2.615277843709764, 'reg_lambda': 2.222670969588794}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:30,786] Trial 35 finished with value: 26.464960504341843 and parameters: {'iterations': 1419, 'learning_rate': 0.1826308077490065, 'depth': 6, 'min_data_in_leaf': 49, 'subsample': 0.765113085936092, 'random_strength': 2.0409200184381167, 'reg_lambda': 3.3188338430879667}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:35,225] Trial 36 finished with value: 26.465272220611077 and parameters: {'iterations': 1012, 'learning_rate': 0.1333447398453506, 'depth': 7, 'min_data_in_leaf': 46, 'subsample': 0.7240106383721572, 'random_strength': 1.2643820566106925, 'reg_lambda': 2.921814786482093}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:40,623] Trial 37 finished with value: 26.46492695680803 and parameters: {'iterations': 2983, 'learning_rate': 0.09187744978359268, 'depth': 4, 'min_data_in_leaf': 24, 'subsample': 0.7822664703891943, 'random_strength': 1.7551888895568808, 'reg_lambda': 2.3107011128410506}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:49,522] Trial 38 finished with value: 26.46430238194994 and parameters: {'iterations': 1466, 'learning_rate': 0.018867211955745866, 'depth': 6, 'min_data_in_leaf': 15, 'subsample': 0.681326446063174, 'random_strength': 2.726904646000767, 'reg_lambda': 1.4265809440317574}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:37:58,269] Trial 39 finished with value: 26.464425252993333 and parameters: {'iterations': 1452, 'learning_rate': 0.013077115382788593, 'depth': 6, 'min_data_in_leaf': 17, 'subsample': 0.6272599941835523, 'random_strength': 2.985591152686837, 'reg_lambda': 1.4974961102723987}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:38:06,023] Trial 40 finished with value: 26.46459096701069 and parameters: {'iterations': 1233, 'learning_rate': 0.026510199765026957, 'depth': 7, 'min_data_in_leaf': 14, 'subsample': 0.7508036871596024, 'random_strength': 2.7994465385311154, 'reg_lambda': 0.6725443436903865}. Best is trial 13 with value: 26.46408516706332.
[I 2025-09-26 11:38:12,899] Trial 41 finished with value: 26.464082502856815 and parameters: {'iterations': 1657, 'learning_rate': 0.03531572711279421, 'depth': 5, 'min_data_in_leaf': 9, 'subsample': 0.6744651421348123, 'random_strength': 2.6550074836163087, 'reg_lambda': 2.6349026625079026}. Best is trial 41 with value: 26.464082502856815.
[I 2025-09-26 11:38:19,296] Trial 42 finished with value: 26.464566444840994 and parameters: {'iterations': 1178, 'learning_rate': 0.03233974954654696, 'depth': 6, 'min_data_in_leaf': 6, 'subsample': 0.6762648498683439, 'random_strength': 2.614804586023853, 'reg_lambda': 2.537336927208094}. Best is trial 41 with value: 26.464082502856815.
[I 2025-09-26 11:38:25,279] Trial 43 finished with value: 26.464453619865616 and parameters: {'iterations': 1342, 'learning_rate': 0.04964875753246546, 'depth': 5, 'min_data_in_leaf': 8, 'subsample': 0.6458230359485807, 'random_strength': 2.79133217391561, 'reg_lambda': 1.5542073722470793}. Best is trial 41 with value: 26.464082502856815.
[I 2025-09-26 11:38:32,275] Trial 44 finished with value: 26.464611757496517 and parameters: {'iterations': 1615, 'learning_rate': 0.038745556230569675, 'depth': 4, 'min_data_in_leaf': 15, 'subsample': 0.9994563730237144, 'random_strength': 2.475979871974955, 'reg_lambda': 3.184772321628317}. Best is trial 41 with value: 26.464082502856815.
[I 2025-09-26 11:38:46,101] Trial 45 finished with value: 26.46448120348275 and parameters: {'iterations': 2135, 'learning_rate': 0.010552171829615022, 'depth': 5, 'min_data_in_leaf': 10, 'subsample': 0.7129465673143275, 'random_strength': 2.6749708087477195, 'reg_lambda': 2.439495952886799}. Best is trial 41 with value: 26.464082502856815.
[I 2025-09-26 11:38:51,912] Trial 46 finished with value: 26.464352409400327 and parameters: {'iterations': 1518, 'learning_rate': 0.07610668862507047, 'depth': 6, 'min_data_in_leaf': 6, 'subsample': 0.6206920566736871, 'random_strength': 1.1289521968178626, 'reg_lambda': 2.8512480340852093}. Best is trial 41 with value: 26.464082502856815.
[I 2025-09-26 11:38:57,682] Trial 47 finished with value: 26.46462906177918 and parameters: {'iterations': 1518, 'learning_rate': 0.07184974981941736, 'depth': 6, 'min_data_in_leaf': 5, 'subsample': 0.6797085361153599, 'random_strength': 1.1458754075476665, 'reg_lambda': 2.7956680437282495}. Best is trial 41 with value: 26.464082502856815.
[I 2025-09-26 11:39:02,875] Trial 48 finished with value: 26.464603623331346 and parameters: {'iterations': 1940, 'learning_rate': 0.05749576018877327, 'depth': 6, 'min_data_in_leaf': 9, 'subsample': 0.6158746519123651, 'random_strength': 0.8777864420606967, 'reg_lambda': 3.072928030164655}. Best is trial 41 with value: 26.464082502856815.
[I 2025-09-26 11:39:09,568] Trial 49 finished with value: 26.464075488132192 and parameters: {'iterations': 2084, 'learning_rate': 0.02825151288259011, 'depth': 7, 'min_data_in_leaf': 12, 'subsample': 0.6586602020967229, 'random_strength': 1.3411061167290226, 'reg_lambda': 3.431505554633282}. Best is trial 49 with value: 26.464075488132192.
[I 2025-09-26 11:39:16,711] Trial 50 finished with value: 26.464507269502235 and parameters: {'iterations': 2586, 'learning_rate': 0.024394086742175556, 'depth': 8, 'min_data_in_leaf': 18, 'subsample': 0.7475110185126228, 'random_strength': 1.3959224777842267, 'reg_lambda': 3.955269227183227}. Best is trial 49 with value: 26.464075488132192.
[I 2025-09-26 11:39:21,742] Trial 51 finished with value: 26.464808710555452 and parameters: {'iterations': 2075, 'learning_rate': 0.0740741866870796, 'depth': 7, 'min_data_in_leaf': 13, 'subsample': 0.6624191311598251, 'random_strength': 1.064972675256168, 'reg_lambda': 3.527652811181275}. Best is trial 49 with value: 26.464075488132192.
[I 2025-09-26 11:39:28,376] Trial 52 finished with value: 26.464756742382654 and parameters: {'iterations': 1682, 'learning_rate': 0.041472774043614956, 'depth': 8, 'min_data_in_leaf': 7, 'subsample': 0.6554004715727525, 'random_strength': 1.2625475120388376, 'reg_lambda': 3.214209409355609}. Best is trial 49 with value: 26.464075488132192.
[I 2025-09-26 11:39:33,812] Trial 53 finished with value: 26.464181943780954 and parameters: {'iterations': 2257, 'learning_rate': 0.05233203760132848, 'depth': 7, 'min_data_in_leaf': 11, 'subsample': 0.6110677190043765, 'random_strength': 1.5238908986988884, 'reg_lambda': 2.615565441604536}. Best is trial 49 with value: 26.464075488132192.
[I 2025-09-26 11:39:39,947] Trial 54 finished with value: 26.464401204454465 and parameters: {'iterations': 2275, 'learning_rate': 0.05531096891340607, 'depth': 7, 'min_data_in_leaf': 11, 'subsample': 0.7061812135575102, 'random_strength': 1.578905014284736, 'reg_lambda': 2.6036218049380273}. Best is trial 49 with value: 26.464075488132192.
[I 2025-09-26 11:39:47,845] Trial 55 finished with value: 26.46461134279111 and parameters: {'iterations': 2390, 'learning_rate': 0.03073204482953679, 'depth': 8, 'min_data_in_leaf': 16, 'subsample': 0.686080594302359, 'random_strength': 1.4979116789088769, 'reg_lambda': 3.366588109559219}. Best is trial 49 with value: 26.464075488132192.
[I 2025-09-26 11:39:55,281] Trial 56 finished with value: 26.464349050696562 and parameters: {'iterations': 2169, 'learning_rate': 0.020329874965678903, 'depth': 7, 'min_data_in_leaf': 12, 'subsample': 0.7199520301924065, 'random_strength': 1.6993961411091338, 'reg_lambda': 1.9145588144403503}. Best is trial 49 with value: 26.464075488132192.
[I 2025-09-26 11:40:02,985] Trial 57 finished with value: 26.4650229857525 and parameters: {'iterations': 2636, 'learning_rate': 0.038059150556734186, 'depth': 10, 'min_data_in_leaf': 27, 'subsample': 0.6082216265857721, 'random_strength': 1.548446658096416, 'reg_lambda': 3.953652658185403}. Best is trial 49 with value: 26.464075488132192.

[I 2025-09-26 11:45:56,422] A new study created in memory with name: no-name-28aa2c0d-ca91-400c-b347-789c804a3011

CatBoost OOF RMSE: 26.4641
==================================================
CREATING STACKED ENSEMBLE WITH TUNED META-MODELS
==================================================
Stacking features shape: (471748, 3)
Individual model correlations:
LGBM vs XGB: 0.7882
LGBM vs CB: 0.8273
XGB vs CB: 0.8238

Tuning meta-models...
Tuning Ridge...

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2025-09-26 11:45:56,632] Trial 0 finished with value: 26.462883607594385 and parameters: {'alpha': 0.13292918943162169}. Best is trial 0 with value: 26.462883607594385.
[I 2025-09-26 11:45:56,835] Trial 1 finished with value: 26.46288359054123 and parameters: {'alpha': 7.114476009343421}. Best is trial 1 with value: 26.46288359054123.
[I 2025-09-26 11:45:57,032] Trial 2 finished with value: 26.462883604081583 and parameters: {'alpha': 1.5702970884055387}. Best is trial 1 with value: 26.46288359054123.
[I 2025-09-26 11:45:57,228] Trial 3 finished with value: 26.462883606391365 and parameters: {'alpha': 0.6251373574521749}. Best is trial 1 with value: 26.46288359054123.
[I 2025-09-26 11:45:57,496] Trial 4 finished with value: 26.462883607847495 and parameters: {'alpha': 0.02938027938703535}. Best is trial 1 with value: 26.46288359054123.
[I 2025-09-26 11:45:57,693] Trial 5 finished with value: 26.462883607847505 and parameters: {'alpha': 0.029375384576328288}. Best is trial 1 with value: 26.46288359054123.
[I 2025-09-26 11:45:57,890] Trial 6 finished with value: 26.462883607882798 and parameters: {'alpha': 0.014936568554617643}. Best is trial 1 with value: 26.46288359054123.
[I 2025-09-26 11:45:58,111] Trial 7 finished with value: 26.462883598224938 and parameters: {'alpha': 3.9676050770529883}. Best is trial 1 with value: 26.46288359054123.
[I 2025-09-26 11:45:58,329] Trial 8 finished with value: 26.46288360636522 and parameters: {'alpha': 0.6358358856676253}. Best is trial 1 with value: 26.46288359054123.
[I 2025-09-26 11:45:58,589] Trial 9 finished with value: 26.46288360466604 and parameters: {'alpha': 1.3311216080736887}. Best is trial 1 with value: 26.46288359054123.
[I 2025-09-26 11:45:58,801] Trial 10 finished with value: 26.46288358672216 and parameters: {'alpha': 8.67929667936377}. Best is trial 10 with value: 26.46288358672216.
[I 2025-09-26 11:45:59,009] Trial 11 finished with value: 26.46288359255619 and parameters: {'alpha': 6.2890637904931594}. Best is trial 10 with value: 26.46288358672216.
[I 2025-09-26 11:45:59,225] Trial 12 finished with value: 26.46288358813009 and parameters: {'alpha': 8.102356207766633}. Best is trial 10 with value: 26.46288358672216.
[I 2025-09-26 11:45:59,431] Trial 13 finished with value: 26.462883601588647 and parameters: {'alpha': 2.590596269534509}. Best is trial 10 with value: 26.46288358672216.
[I 2025-09-26 11:45:59,636] Trial 14 finished with value: 26.462883584974726 and parameters: {'alpha': 9.395445020858189}. Best is trial 14 with value: 26.462883584974726.
[I 2025-09-26 11:45:59,835] Trial 15 finished with value: 26.462883607656426 and parameters: {'alpha': 0.10754807276403053}. Best is trial 14 with value: 26.462883584974726.
[I 2025-09-26 11:46:00,042] Trial 16 finished with value: 26.462883601091526 and parameters: {'alpha': 2.7940792809636092}. Best is trial 14 with value: 26.462883584974726.
[I 2025-09-26 11:46:00,249] Trial 17 finished with value: 26.46288360689838 and parameters: {'alpha': 0.4176927038877977}. Best is trial 14 with value: 26.462883584974726.
[I 2025-09-26 11:46:00,469] Trial 18 finished with value: 26.46288360406073 and parameters: {'alpha': 1.5788313208568319}. Best is trial 14 with value: 26.462883584974726.
[I 2025-09-26 11:46:00,683] Trial 19 finished with value: 26.46288358387914 and parameters: {'alpha': 9.844498380225962}. Best is trial 19 with value: 26.46288358387914.
[I 2025-09-26 11:46:00,891] Trial 20 finished with value: 26.462883607396215 and parameters: {'alpha': 0.21400865563866026}. Best is trial 19 with value: 26.46288358387914.
[I 2025-09-26 11:46:01,091] Trial 21 finished with value: 26.462883587268113 and parameters: {'alpha': 8.455569311568896}. Best is trial 19 with value: 26.46288358387914.
[I 2025-09-26 11:46:01,297] Trial 22 finished with value: 26.462883598281273 and parameters: {'alpha': 3.9445385457661204}. Best is trial 19 with value: 26.46288358387914.
[I 2025-09-26 11:46:01,505] Trial 23 finished with value: 26.462883584819753 and parameters: {'alpha': 9.45896239299366}. Best is trial 19 with value: 26.46288358387914.
[I 2025-09-26 11:46:01,712] Trial 24 finished with value: 26.4628835967227 and parameters: {'alpha': 4.58269670299207}. Best is trial 19 with value: 26.46288358387914.
[I 2025-09-26 11:46:01,915] Trial 25 finished with value: 26.462883602343776 and parameters: {'alpha': 2.281520170213827}. Best is trial 19 with value: 26.46288358387914.
[I 2025-09-26 11:46:02,117] Trial 26 finished with value: 26.462883605810894 and parameters: {'alpha': 0.862649136577457}. Best is trial 19 with value: 26.46288358387914.
[I 2025-09-26 11:46:02,319] Trial 27 finished with value: 26.462883583632653 and parameters: {'alpha': 9.94553372821432}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:02,518] Trial 28 finished with value: 26.462883596327295 and parameters: {'alpha': 4.744609008809301}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:02,721] Trial 29 finished with value: 26.462883607563732 and parameters: {'alpha': 0.1454730727129809}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:02,922] Trial 30 finished with value: 26.462883601019136 and parameters: {'alpha': 2.8237107478432426}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:03,157] Trial 31 finished with value: 26.46288358370696 and parameters: {'alpha': 9.915072834529177}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:03,374] Trial 32 finished with value: 26.462883594298823 and parameters: {'alpha': 5.57530947831504}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:03,591] Trial 33 finished with value: 26.462883594735075 and parameters: {'alpha': 5.396643817856746}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:03,809] Trial 34 finished with value: 26.4628835844208 and parameters: {'alpha': 9.622479075484385}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:04,033] Trial 35 finished with value: 26.462883603475507 and parameters: {'alpha': 1.818332001385502}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:04,256] Trial 36 finished with value: 26.46288359960879 and parameters: {'alpha': 3.401049030680416}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:04,472] Trial 37 finished with value: 26.46288360535065 and parameters: {'alpha': 1.0509751486396284}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:04,690] Trial 38 finished with value: 26.462883607777076 and parameters: {'alpha': 0.058189825871060925}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:04,909] Trial 39 finished with value: 26.462883592189645 and parameters: {'alpha': 6.439204448095427}. Best is trial 27 with value: 26.462883583632653.
[I 2025-09-26 11:46:05,252] Trial 40 finished with value: 26.46288358360698 and parameters: {'alpha': 9.956055660659027}. Best is trial 40 with value: 26.46288358360698.
[I 2025-09-26 11:46:05,464] Trial 41 finished with value: 26.46288359238657 and parameters: {'alpha': 6.358538878609044}. Best is trial 40 with value: 26.46288358360698.
[I 2025-09-26 11:46:05,677] Trial 42 finished with value: 26.462883598164854 and parameters: {'alpha': 3.9922047204485547}. Best is trial 40 with value: 26.46288358360698.
[I 2025-09-26 11:46:05,877] Trial 43 finished with value: 26.462883583678206 and parameters: {'alpha': 9.926860448056077}. Best is trial 40 with value: 26.46288358360698.
[I 2025-09-26 11:46:06,075] Trial 44 finished with value: 26.46288359338567 and parameters: {'alpha': 5.949308422686077}. Best is trial 40 with value: 26.46288358360698.
[I 2025-09-26 11:46:06,273] Trial 45 finished with value: 26.46288358359959 and parameters: {'alpha': 9.959085058671077}. Best is trial 45 with value: 26.46288358359959.
[I 2025-09-26 11:46:06,471] Trial 46 finished with value: 26.462883590390998 and parameters: {'alpha': 7.176023166906812}. Best is trial 45 with value: 26.46288358359959.
[I 2025-09-26 11:46:06,668] Trial 47 finished with value: 26.462883603040165 and parameters: {'alpha': 1.9965010884234253}. Best is trial 45 with value: 26.46288358359959.
[I 2025-09-26 11:46:06,866] Trial 48 finished with value: 26.4628836000543 and parameters: {'alpha': 3.2186679716746727}. Best is trial 45 with value: 26.46288358359959.
[I 2025-09-26 11:46:07,063] Trial 49 finished with value: 26.462883590741 and parameters: {'alpha': 7.03263534453934}. Best is trial 45 with value: 26.46288358359959.
Best Ridge RMSE: 26.4629
Tuning ElasticNet...

[I 2025-09-26 11:46:07,266] A new study created in memory with name: no-name-c5b024ce-16ed-4332-8211-911c75031903

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2025-09-26 11:46:07,529] Trial 0 finished with value: 26.463772979572674 and parameters: {'alpha': 0.13292918943162169, 'l1_ratio': 0.8605714451279329}. Best is trial 0 with value: 26.463772979572674.
[I 2025-09-26 11:46:07,712] Trial 1 finished with value: 26.47315427104515 and parameters: {'alpha': 1.5702970884055387, 'l1_ratio': 0.5789267873576293}. Best is trial 0 with value: 26.463772979572674.
[I 2025-09-26 11:46:07,932] Trial 2 finished with value: 26.4628853701846 and parameters: {'alpha': 0.02938027938703535, 'l1_ratio': 0.22479561626896213}. Best is trial 2 with value: 26.4628853701846.
[I 2025-09-26 11:46:08,165] Trial 3 finished with value: 26.46289119163446 and parameters: {'alpha': 0.014936568554617643, 'l1_ratio': 0.7929409166199481}. Best is trial 2 with value: 26.4628853701846.
[I 2025-09-26 11:46:08,352] Trial 4 finished with value: 26.472285289173975 and parameters: {'alpha': 0.6358358856676253, 'l1_ratio': 0.6664580622368363}. Best is trial 2 with value: 26.4628853701846.
[I 2025-09-26 11:46:08,593] Trial 5 finished with value: 26.462889131318157 and parameters: {'alpha': 0.011527987128232402, 'l1_ratio': 0.8759278817295955}. Best is trial 2 with value: 26.4628853701846.
[I 2025-09-26 11:46:08,779] Trial 6 finished with value: 26.47315427104515 and parameters: {'alpha': 3.142880890840109, 'l1_ratio': 0.26987128854262094}. Best is trial 2 with value: 26.4628853701846.
[I 2025-09-26 11:46:09,000] Trial 7 finished with value: 26.46289146117892 and parameters: {'alpha': 0.035113563139704075, 'l1_ratio': 0.24672360788274705}. Best is trial 2 with value: 26.4628853701846.
[I 2025-09-26 11:46:09,219] Trial 8 finished with value: 26.46306124132652 and parameters: {'alpha': 0.08179499475211674, 'l1_ratio': 0.5198051453057903}. Best is trial 2 with value: 26.4628853701846.
[I 2025-09-26 11:46:09,429] Trial 9 finished with value: 26.463560555336393 and parameters: {'alpha': 0.19762189340280073, 'l1_ratio': 0.3329833121584336}. Best is trial 2 with value: 26.4628853701846.
[I 2025-09-26 11:46:09,616] Trial 10 finished with value: 26.47315427104515 and parameters: {'alpha': 6.8455702672729, 'l1_ratio': 0.10479774636465389}. Best is trial 2 with value: 26.4628853701846.
[I 2025-09-26 11:46:10,032] Trial 11 finished with value: 26.462880976562893 and parameters: {'alpha': 0.010535179945522749, 'l1_ratio': 0.3849642546665958}. Best is trial 11 with value: 26.462880976562893.
[I 2025-09-26 11:46:10,452] Trial 12 finished with value: 26.46289799423294 and parameters: {'alpha': 0.032922850572621884, 'l1_ratio': 0.4037611702291196}. Best is trial 11 with value: 26.462880976562893.
[I 2025-09-26 11:46:10,795] Trial 13 finished with value: 26.462893652633785 and parameters: {'alpha': 0.04539188693039218, 'l1_ratio': 0.11023355107533167}. Best is trial 11 with value: 26.462880976562893.
[I 2025-09-26 11:46:11,037] Trial 14 finished with value: 26.466070605332153 and parameters: {'alpha': 0.43921253191761606, 'l1_ratio': 0.41376371587694427}. Best is trial 11 with value: 26.462880976562893.
[I 2025-09-26 11:46:11,304] Trial 15 finished with value: 26.462879100609086 and parameters: {'alpha': 0.010601886434912396, 'l1_ratio': 0.21292354332742486}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:11,594] Trial 16 finished with value: 26.462881440833293 and parameters: {'alpha': 0.010910499555167963, 'l1_ratio': 0.4195850250666826}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:11,847] Trial 17 finished with value: 26.462923734797055 and parameters: {'alpha': 0.06120883822410409, 'l1_ratio': 0.19458604091364448}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:12,165] Trial 18 finished with value: 26.462885297818968 and parameters: {'alpha': 0.022877359307757746, 'l1_ratio': 0.3539432417843734}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:12,545] Trial 19 finished with value: 26.463226588132756 and parameters: {'alpha': 0.10285957829382783, 'l1_ratio': 0.6166851525625929}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:12,747] Trial 20 finished with value: 26.473132015150913 and parameters: {'alpha': 0.9099331358034507, 'l1_ratio': 0.5150905623048867}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:13,001] Trial 21 finished with value: 26.462881505095915 and parameters: {'alpha': 0.01109113107540255, 'l1_ratio': 0.42241128977058423}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:13,243] Trial 22 finished with value: 26.462882131446776 and parameters: {'alpha': 0.018845115227534688, 'l1_ratio': 0.32400114330044194}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:13,475] Trial 23 finished with value: 26.462881690123396 and parameters: {'alpha': 0.010411488714524327, 'l1_ratio': 0.4456883561932956}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:13,703] Trial 24 finished with value: 26.46287936684147 and parameters: {'alpha': 0.020647615499015066, 'l1_ratio': 0.17536228336852452}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:13,910] Trial 25 finished with value: 26.463442238548122 and parameters: {'alpha': 0.2213867989420901, 'l1_ratio': 0.16921290192250243}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:14,140] Trial 26 finished with value: 26.46288188901484 and parameters: {'alpha': 0.020640328765382878, 'l1_ratio': 0.2813287083290644}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:14,380] Trial 27 finished with value: 26.46291537259568 and parameters: {'alpha': 0.05814508662528523, 'l1_ratio': 0.16841406446625826}. Best is trial 15 with value: 26.462879100609086.
[I 2025-09-26 11:46:14,639] Trial 28 finished with value: 26.46287866870457 and parameters: {'alpha': 0.02002952164154716, 'l1_ratio': 0.15015821142842917}. Best is trial 28 with value: 26.46287866870457.
[I 2025-09-26 11:46:14,868] Trial 29 finished with value: 26.463112728692387 and parameters: {'alpha': 0.14178368738957675, 'l1_ratio': 0.14315555025095061}. Best is trial 28 with value: 26.46287866870457.
[I 2025-09-26 11:46:15,108] Trial 30 finished with value: 26.462902047795723 and parameters: {'alpha': 0.04514139522750069, 'l1_ratio': 0.22641625489340242}. Best is trial 28 with value: 26.46287866870457.
[I 2025-09-26 11:46:15,332] Trial 31 finished with value: 26.46288227361476 and parameters: {'alpha': 0.0206459418562037, 'l1_ratio': 0.29610169080863213}. Best is trial 28 with value: 26.46287866870457.
[I 2025-09-26 11:46:15,555] Trial 32 finished with value: 26.462878722363776 and parameters: {'alpha': 0.01538432967969253, 'l1_ratio': 0.1932111926815331}. Best is trial 28 with value: 26.46287866870457.
[I 2025-09-26 11:46:15,784] Trial 33 finished with value: 26.462883366197183 and parameters: {'alpha': 0.026975951217323477, 'l1_ratio': 0.21529472573608013}. Best is trial 28 with value: 26.46287866870457.
[I 2025-09-26 11:46:16,009] Trial 34 finished with value: 26.462877952712763 and parameters: {'alpha': 0.01479000627710483, 'l1_ratio': 0.14194329268157713}. Best is trial 34 with value: 26.462877952712763.
[I 2025-09-26 11:46:16,243] Trial 35 finished with value: 26.462892324057986 and parameters: {'alpha': 0.01587325844414024, 'l1_ratio': 0.7903418574826024}. Best is trial 34 with value: 26.462877952712763.
[I 2025-09-26 11:46:16,557] Trial 36 finished with value: 26.46288774161256 and parameters: {'alpha': 0.0374771155120091, 'l1_ratio': 0.13520109479258904}. Best is trial 34 with value: 26.462877952712763.
[I 2025-09-26 11:46:16,864] Trial 37 finished with value: 26.462879807765518 and parameters: {'alpha': 0.016717792311492796, 'l1_ratio': 0.24617339438337535}. Best is trial 34 with value: 26.462877952712763.
[I 2025-09-26 11:46:17,166] Trial 38 finished with value: 26.46292904762 and parameters: {'alpha': 0.072154675668356, 'l1_ratio': 0.1025190539384206}. Best is trial 34 with value: 26.462877952712763.
[I 2025-09-26 11:46:17,382] Trial 39 finished with value: 26.47265994099099 and parameters: {'alpha': 1.9554295990246573, 'l1_ratio': 0.2052913778751912}. Best is trial 34 with value: 26.462877952712763.
[I 2025-09-26 11:46:17,630] Trial 40 finished with value: 26.462880313092864 and parameters: {'alpha': 0.014988999119924191, 'l1_ratio': 0.29525858254851545}. Best is trial 34 with value: 26.462877952712763.
[I 2025-09-26 11:46:17,855] Trial 41 finished with value: 26.462884752793478 and parameters: {'alpha': 0.031329850828323326, 'l1_ratio': 0.17457043010445902}. Best is trial 34 with value: 26.462877952712763.
[I 2025-09-26 11:46:18,079] Trial 42 finished with value: 26.4628782393641 and parameters: {'alpha': 0.014597008428329162, 'l1_ratio': 0.1624894865799773}. Best is trial 34 with value: 26.462877952712763.
[I 2025-09-26 11:46:18,305] Trial 43 finished with value: 26.46287796659962 and parameters: {'alpha': 0.013776307763872241, 'l1_ratio': 0.14074802046285348}. Best is trial 34 with value: 26.462877952712763.
[I 2025-09-26 11:46:18,530] Trial 44 finished with value: 26.462877936866875 and parameters: {'alpha': 0.01442230231659227, 'l1_ratio': 0.140205537510819}. Best is trial 44 with value: 26.462877936866875.
[I 2025-09-26 11:46:18,752] Trial 45 finished with value: 26.462880533049184 and parameters: {'alpha': 0.026176631155456306, 'l1_ratio': 0.13991799890208895}. Best is trial 44 with value: 26.462877936866875.
[I 2025-09-26 11:46:18,978] Trial 46 finished with value: 26.46289344246179 and parameters: {'alpha': 0.04311706498827461, 'l1_ratio': 0.14193909362549595}. Best is trial 44 with value: 26.462877936866875.
[I 2025-09-26 11:46:19,246] Trial 47 finished with value: 26.462879508343853 and parameters: {'alpha': 0.013791380012436572, 'l1_ratio': 0.25423100050440667}. Best is trial 44 with value: 26.462877936866875.
[I 2025-09-26 11:46:19,556] Trial 48 finished with value: 26.462908391046778 and parameters: {'alpha': 0.027842671784230128, 'l1_ratio': 0.6969106478450141}. Best is trial 44 with value: 26.462877936866875.
[I 2025-09-26 11:46:19,750] Trial 49 finished with value: 26.47315427104515 and parameters: {'alpha': 6.032936984631044, 'l1_ratio': 0.12249789857855978}. Best is trial 44 with value: 26.462877936866875.
Best ElasticNet RMSE: 26.4629

[I 2025-09-26 11:46:20,027] A new study created in memory with name: no-name-bba0beca-a21a-42bf-bc69-602fee471ffc

Tuning LightGBM_Meta...

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2025-09-26 11:46:25,559] Trial 0 finished with value: 26.645539360963397 and parameters: {'n_estimators': 218, 'learning_rate': 0.28570714885887566, 'max_depth': 7, 'num_leaves': 64}. Best is trial 0 with value: 26.645539360963397.
[I 2025-09-26 11:46:27,568] Trial 1 finished with value: 26.463048850634124 and parameters: {'n_estimators': 120, 'learning_rate': 0.055238410897498764, 'max_depth': 2, 'num_leaves': 88}. Best is trial 1 with value: 26.463048850634124.
[I 2025-09-26 11:46:31,443] Trial 2 finished with value: 26.469458925893868 and parameters: {'n_estimators': 321, 'learning_rate': 0.21534104756085318, 'max_depth': 2, 'num_leaves': 98}. Best is trial 1 with value: 26.463048850634124.
[I 2025-09-26 11:46:36,455] Trial 3 finished with value: 26.470603415877918 and parameters: {'n_estimators': 425, 'learning_rate': 0.07157834209670008, 'max_depth': 3, 'num_leaves': 26}. Best is trial 1 with value: 26.463048850634124.
[I 2025-09-26 11:46:39,847] Trial 4 finished with value: 26.497560052555308 and parameters: {'n_estimators': 187, 'learning_rate': 0.16217936517334897, 'max_depth': 5, 'num_leaves': 36}. Best is trial 1 with value: 26.463048850634124.
[I 2025-09-26 11:46:44,415] Trial 5 finished with value: 26.47128446946072 and parameters: {'n_estimators': 325, 'learning_rate': 0.05045321958909213, 'max_depth': 4, 'num_leaves': 43}. Best is trial 1 with value: 26.463048850634124.
[I 2025-09-26 11:46:47,696] Trial 6 finished with value: 26.481773061084645 and parameters: {'n_estimators': 255, 'learning_rate': 0.23770102880397392, 'max_depth': 3, 'num_leaves': 56}. Best is trial 1 with value: 26.463048850634124.
[I 2025-09-26 11:46:54,688] Trial 7 finished with value: 26.468077080328328 and parameters: {'n_estimators': 317, 'learning_rate': 0.02347061968879934, 'max_depth': 6, 'num_leaves': 25}. Best is trial 1 with value: 26.463048850634124.
[I 2025-09-26 11:46:57,332] Trial 8 finished with value: 26.55069664836044 and parameters: {'n_estimators': 79, 'learning_rate': 0.2851768058034666, 'max_depth': 8, 'num_leaves': 83}. Best is trial 1 with value: 26.463048850634124.
[I 2025-09-26 11:47:02,547] Trial 9 finished with value: 26.472211574092956 and parameters: {'n_estimators': 187, 'learning_rate': 0.03832491306185132, 'max_depth': 6, 'num_leaves': 50}. Best is trial 1 with value: 26.463048850634124.
[I 2025-09-26 11:47:03,938] Trial 10 finished with value: 26.463096806669324 and parameters: {'n_estimators': 59, 'learning_rate': 0.11548102535027302, 'max_depth': 2, 'num_leaves': 75}. Best is trial 1 with value: 26.463048850634124.
[I 2025-09-26 11:47:05,295] Trial 11 finished with value: 26.4629941484503 and parameters: {'n_estimators': 56, 'learning_rate': 0.10972158779277433, 'max_depth': 2, 'num_leaves': 80}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:06,944] Trial 12 finished with value: 26.466678779160084 and parameters: {'n_estimators': 119, 'learning_rate': 0.12008523059186482, 'max_depth': 3, 'num_leaves': 96}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:08,933] Trial 13 finished with value: 26.463694475838714 and parameters: {'n_estimators': 129, 'learning_rate': 0.09421561674794705, 'max_depth': 2, 'num_leaves': 80}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:11,026] Trial 14 finished with value: 26.476189302818266 and parameters: {'n_estimators': 131, 'learning_rate': 0.16277202762265797, 'max_depth': 4, 'num_leaves': 68}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:17,642] Trial 15 finished with value: 26.483996850441777 and parameters: {'n_estimators': 461, 'learning_rate': 0.07983430187526397, 'max_depth': 4, 'num_leaves': 88}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:18,570] Trial 16 finished with value: 26.463151742770698 and parameters: {'n_estimators': 56, 'learning_rate': 0.13263341206664664, 'max_depth': 2, 'num_leaves': 69}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:21,324] Trial 17 finished with value: 26.463369701098724 and parameters: {'n_estimators': 159, 'learning_rate': 0.0107970871590308, 'max_depth': 3, 'num_leaves': 89}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:24,422] Trial 18 finished with value: 26.484670390110985 and parameters: {'n_estimators': 91, 'learning_rate': 0.20238786429747496, 'max_depth': 5, 'num_leaves': 100}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:31,597] Trial 19 finished with value: 26.475171836561696 and parameters: {'n_estimators': 379, 'learning_rate': 0.05937726679494487, 'max_depth': 4, 'num_leaves': 76}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:36,400] Trial 20 finished with value: 26.46441627722603 and parameters: {'n_estimators': 236, 'learning_rate': 0.09392176086813098, 'max_depth': 2, 'num_leaves': 59}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:37,353] Trial 21 finished with value: 26.463322486356805 and parameters: {'n_estimators': 67, 'learning_rate': 0.12163523953199173, 'max_depth': 2, 'num_leaves': 74}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:38,658] Trial 22 finished with value: 26.46476537360803 and parameters: {'n_estimators': 54, 'learning_rate': 0.14315054090773313, 'max_depth': 3, 'num_leaves': 88}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:40,890] Trial 23 finished with value: 26.46375939706895 and parameters: {'n_estimators': 113, 'learning_rate': 0.10574539819601693, 'max_depth': 2, 'num_leaves': 11}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:43,946] Trial 24 finished with value: 26.472240800139595 and parameters: {'n_estimators': 164, 'learning_rate': 0.19153939819967575, 'max_depth': 3, 'num_leaves': 74}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:45,880] Trial 25 finished with value: 26.46326323848689 and parameters: {'n_estimators': 99, 'learning_rate': 0.08013439788438644, 'max_depth': 2, 'num_leaves': 82}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:47,262] Trial 26 finished with value: 26.46325170694389 and parameters: {'n_estimators': 50, 'learning_rate': 0.04234052813204185, 'max_depth': 3, 'num_leaves': 63}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:50,118] Trial 27 finished with value: 26.464132256956475 and parameters: {'n_estimators': 152, 'learning_rate': 0.10916615206665548, 'max_depth': 2, 'num_leaves': 91}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:51,642] Trial 28 finished with value: 26.472090561307716 and parameters: {'n_estimators': 93, 'learning_rate': 0.16747999745749464, 'max_depth': 4, 'num_leaves': 49}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:47:55,318] Trial 29 finished with value: 26.523461146582015 and parameters: {'n_estimators': 190, 'learning_rate': 0.13620637331676277, 'max_depth': 8, 'num_leaves': 67}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:02,588] Trial 30 finished with value: 26.497808316907538 and parameters: {'n_estimators': 220, 'learning_rate': 0.06856475722509218, 'max_depth': 7, 'num_leaves': 80}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:03,695] Trial 31 finished with value: 26.46337101145869 and parameters: {'n_estimators': 75, 'learning_rate': 0.13677342118810112, 'max_depth': 2, 'num_leaves': 70}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:04,671] Trial 32 finished with value: 26.46315173539198 and parameters: {'n_estimators': 56, 'learning_rate': 0.12481526283106724, 'max_depth': 2, 'num_leaves': 62}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:06,954] Trial 33 finished with value: 26.468032147011996 and parameters: {'n_estimators': 105, 'learning_rate': 0.18570655148157914, 'max_depth': 3, 'num_leaves': 62}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:10,045] Trial 34 finished with value: 26.463780402349556 and parameters: {'n_estimators': 141, 'learning_rate': 0.09060843620543044, 'max_depth': 2, 'num_leaves': 92}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:13,913] Trial 35 finished with value: 26.46563224911781 and parameters: {'n_estimators': 285, 'learning_rate': 0.11403764965917443, 'max_depth': 2, 'num_leaves': 84}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:15,394] Trial 36 finished with value: 26.46613188628593 and parameters: {'n_estimators': 80, 'learning_rate': 0.1511216565610135, 'max_depth': 3, 'num_leaves': 76}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:21,039] Trial 37 finished with value: 26.468116308350005 and parameters: {'n_estimators': 381, 'learning_rate': 0.05588194080101953, 'max_depth': 3, 'num_leaves': 55}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:24,568] Trial 38 finished with value: 26.567040566583795 and parameters: {'n_estimators': 176, 'learning_rate': 0.2567938329412942, 'max_depth': 6, 'num_leaves': 96}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:25,850] Trial 39 finished with value: 26.464017599287608 and parameters: {'n_estimators': 77, 'learning_rate': 0.17527258793262468, 'max_depth': 2, 'num_leaves': 35}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:33,272] Trial 40 finished with value: 26.467514067134562 and parameters: {'n_estimators': 500, 'learning_rate': 0.0388310760531836, 'max_depth': 3, 'num_leaves': 51}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:34,083] Trial 41 finished with value: 26.463094824483978 and parameters: {'n_estimators': 51, 'learning_rate': 0.1251587863222563, 'max_depth': 2, 'num_leaves': 72}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:35,242] Trial 42 finished with value: 26.463879927010204 and parameters: {'n_estimators': 110, 'learning_rate': 0.12439043162930032, 'max_depth': 2, 'num_leaves': 72}. Best is trial 11 with value: 26.4629941484503.
[I 2025-09-26 11:48:36,032] Trial 43 finished with value: 26.462872324272837 and parameters: {'n_estimators': 53, 'learning_rate': 0.10205119959516745, 'max_depth': 2, 'num_leaves': 65}. Best is trial 43 with value: 26.462872324272837.
[I 2025-09-26 11:48:37,496] Trial 44 finished with value: 26.463705817772187 and parameters: {'n_estimators': 126, 'learning_rate': 0.10369026941804735, 'max_depth': 2, 'num_leaves': 79}. Best is trial 43 with value: 26.462872324272837.
[I 2025-09-26 11:48:38,536] Trial 45 finished with value: 26.463901010908973 and parameters: {'n_estimators': 75, 'learning_rate': 0.0759209882488037, 'max_depth': 3, 'num_leaves': 86}. Best is trial 43 with value: 26.462872324272837.
[I 2025-09-26 11:48:39,296] Trial 46 finished with value: 26.46334417296726 and parameters: {'n_estimators': 50, 'learning_rate': 0.14772618940527665, 'max_depth': 2, 'num_leaves': 65}. Best is trial 43 with value: 26.462872324272837.
[I 2025-09-26 11:48:40,639] Trial 47 finished with value: 26.467049575809114 and parameters: {'n_estimators': 93, 'learning_rate': 0.08960768433024895, 'max_depth': 4, 'num_leaves': 95}. Best is trial 43 with value: 26.462872324272837.
[I 2025-09-26 11:48:42,079] Trial 48 finished with value: 26.46315562738547 and parameters: {'n_estimators': 119, 'learning_rate': 0.021033737984255244, 'max_depth': 3, 'num_leaves': 77}. Best is trial 43 with value: 26.462872324272837.
[I 2025-09-26 11:48:43,509] Trial 49 finished with value: 26.463215643517355 and parameters: {'n_estimators': 140, 'learning_rate': 0.0611501923474498, 'max_depth': 2, 'num_leaves': 83}. Best is trial 43 with value: 26.462872324272837.
Best LightGBM_Meta RMSE: 26.4629

[I 2025-09-26 11:48:44,487] A new study created in memory with name: no-name-af10b238-f73e-479c-9047-94f289899dc0

==================================================
ADVANCED: MULTI-LEVEL STACKING
==================================================
Tuning Level 2 meta-model...

[I 2025-09-26 11:48:44,678] Trial 0 finished with value: 26.461994781535175 and parameters: {'alpha': 0.13292918943162169}. Best is trial 0 with value: 26.461994781535175.
[I 2025-09-26 11:48:44,872] Trial 1 finished with value: 26.461990569763714 and parameters: {'alpha': 7.114476009343421}. Best is trial 1 with value: 26.461990569763714.
[I 2025-09-26 11:48:45,063] Trial 2 finished with value: 26.4619937231087 and parameters: {'alpha': 1.5702970884055387}. Best is trial 1 with value: 26.461990569763714.
[I 2025-09-26 11:48:45,253] Trial 3 finished with value: 26.461994407272044 and parameters: {'alpha': 0.6251373574521749}. Best is trial 1 with value: 26.461990569763714.
[I 2025-09-26 11:48:45,444] Trial 4 finished with value: 26.461994861860006 and parameters: {'alpha': 0.02938027938703535}. Best is trial 1 with value: 26.461990569763714.
[I 2025-09-26 11:48:45,637] Trial 5 finished with value: 26.461994861863815 and parameters: {'alpha': 0.029375384576328288}. Best is trial 1 with value: 26.461990569763714.
[I 2025-09-26 11:48:45,827] Trial 6 finished with value: 26.46199487310839 and parameters: {'alpha': 0.014936568554617643}. Best is trial 1 with value: 26.461990569763714.
[I 2025-09-26 11:48:46,019] Trial 7 finished with value: 26.461992184586286 and parameters: {'alpha': 3.9676050770529883}. Best is trial 1 with value: 26.461990569763714.
[I 2025-09-26 11:48:46,209] Trial 8 finished with value: 26.461994399274964 and parameters: {'alpha': 0.6358358856676253}. Best is trial 1 with value: 26.461990569763714.
[I 2025-09-26 11:48:46,402] Trial 9 finished with value: 26.461993891994048 and parameters: {'alpha': 1.3311216080736887}. Best is trial 1 with value: 26.461990569763714.
[I 2025-09-26 11:48:46,595] Trial 10 finished with value: 26.461989927442175 and parameters: {'alpha': 8.67929667936377}. Best is trial 10 with value: 26.461989927442175.
[I 2025-09-26 11:48:46,788] Trial 11 finished with value: 26.46199095069274 and parameters: {'alpha': 6.2890637904931594}. Best is trial 10 with value: 26.461989927442175.
[I 2025-09-26 11:48:46,983] Trial 12 finished with value: 26.461990152287548 and parameters: {'alpha': 8.102356207766633}. Best is trial 10 with value: 26.461989927442175.
[I 2025-09-26 11:48:47,177] Trial 13 finished with value: 26.461993034403168 and parameters: {'alpha': 2.590596269534509}. Best is trial 10 with value: 26.461989927442175.
[I 2025-09-26 11:48:47,369] Trial 14 finished with value: 26.461989667417356 and parameters: {'alpha': 9.395445020858189}. Best is trial 14 with value: 26.461989667417356.
[I 2025-09-26 11:48:47,563] Trial 15 finished with value: 26.461994801172448 and parameters: {'alpha': 0.10754807276403053}. Best is trial 14 with value: 26.461989667417356.
[I 2025-09-26 11:48:47,756] Trial 16 finished with value: 26.461992903123512 and parameters: {'alpha': 2.7940792809636092}. Best is trial 14 with value: 26.461989667417356.
[I 2025-09-26 11:48:47,950] Trial 17 finished with value: 26.46199456349181 and parameters: {'alpha': 0.4176927038877977}. Best is trial 14 with value: 26.461989667417356.
[I 2025-09-26 11:48:48,142] Trial 18 finished with value: 26.461993717135243 and parameters: {'alpha': 1.5788313208568319}. Best is trial 14 with value: 26.461989667417356.
[I 2025-09-26 11:48:48,335] Trial 19 finished with value: 26.461989514985486 and parameters: {'alpha': 9.844498380225962}. Best is trial 19 with value: 26.461989514985486.
[I 2025-09-26 11:48:48,528] Trial 20 finished with value: 26.46199471902724 and parameters: {'alpha': 0.21400865563866026}. Best is trial 19 with value: 26.461989514985486.
[I 2025-09-26 11:48:48,721] Trial 21 finished with value: 26.461990012992324 and parameters: {'alpha': 8.455569311568896}. Best is trial 19 with value: 26.461989514985486.
[I 2025-09-26 11:48:48,914] Trial 22 finished with value: 26.46199219808368 and parameters: {'alpha': 3.9445385457661204}. Best is trial 19 with value: 26.461989514985486.
[I 2025-09-26 11:48:49,108] Trial 23 finished with value: 26.461989645362905 and parameters: {'alpha': 9.45896239299366}. Best is trial 19 with value: 26.461989514985486.
[I 2025-09-26 11:48:49,304] Trial 24 finished with value: 26.461991833779564 and parameters: {'alpha': 4.58269670299207}. Best is trial 19 with value: 26.461989514985486.
[I 2025-09-26 11:48:49,496] Trial 25 finished with value: 26.46199323764617 and parameters: {'alpha': 2.281520170213827}. Best is trial 19 with value: 26.461989514985486.
[I 2025-09-26 11:48:49,691] Trial 26 finished with value: 26.46199423110454 and parameters: {'alpha': 0.862649136577457}. Best is trial 19 with value: 26.461989514985486.
[I 2025-09-26 11:48:49,884] Trial 27 finished with value: 26.461989481803904 and parameters: {'alpha': 9.94553372821432}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:50,078] Trial 28 finished with value: 26.461991744336455 and parameters: {'alpha': 4.744609008809301}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:50,271] Trial 29 finished with value: 26.461994771842313 and parameters: {'alpha': 0.1454730727129809}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:50,463] Trial 30 finished with value: 26.461992884172968 and parameters: {'alpha': 2.8237107478432426}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:50,656] Trial 31 finished with value: 26.461989491764804 and parameters: {'alpha': 9.915072834529177}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:50,850] Trial 32 finished with value: 26.461991304188558 and parameters: {'alpha': 5.57530947831504}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:51,042] Trial 33 finished with value: 26.461991396225365 and parameters: {'alpha': 5.396643817856746}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:51,236] Trial 34 finished with value: 26.461989589336184 and parameters: {'alpha': 9.622479075484385}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:51,429] Trial 35 finished with value: 26.46199355097309 and parameters: {'alpha': 1.818332001385502}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:51,621] Trial 36 finished with value: 26.46199252333153 and parameters: {'alpha': 3.401049030680416}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:51,814] Trial 37 finished with value: 26.46199409345265 and parameters: {'alpha': 1.0509751486396284}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:52,007] Trial 38 finished with value: 26.46199483945616 and parameters: {'alpha': 0.058189825871060925}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:52,198] Trial 39 finished with value: 26.46199087919557 and parameters: {'alpha': 6.439204448095427}. Best is trial 27 with value: 26.461989481803904.
[I 2025-09-26 11:48:52,391] Trial 40 finished with value: 26.46198947837177 and parameters: {'alpha': 9.956055660659027}. Best is trial 40 with value: 26.46198947837177.
[I 2025-09-26 11:48:52,582] Trial 41 finished with value: 26.46199091748581 and parameters: {'alpha': 6.358538878609044}. Best is trial 40 with value: 26.46198947837177.
[I 2025-09-26 11:48:52,774] Trial 42 finished with value: 26.461992170219162 and parameters: {'alpha': 3.9922047204485547}. Best is trial 40 with value: 26.46198947837177.
[I 2025-09-26 11:48:52,965] Trial 43 finished with value: 26.461989487905793 and parameters: {'alpha': 9.926860448056077}. Best is trial 40 with value: 26.46198947837177.
[I 2025-09-26 11:48:53,159] Trial 44 finished with value: 26.46199111614513 and parameters: {'alpha': 5.949308422686077}. Best is trial 40 with value: 26.46198947837177.
[I 2025-09-26 11:48:53,351] Trial 45 finished with value: 26.461989477384442 and parameters: {'alpha': 9.959085058671077}. Best is trial 45 with value: 26.461989477384442.
[I 2025-09-26 11:48:53,547] Trial 46 finished with value: 26.46199054254031 and parameters: {'alpha': 7.176023166906812}. Best is trial 45 with value: 26.461989477384442.
[I 2025-09-26 11:48:53,741] Trial 47 finished with value: 26.461993429201677 and parameters: {'alpha': 1.9965010884234253}. Best is trial 45 with value: 26.461989477384442.
[I 2025-09-26 11:48:53,934] Trial 48 finished with value: 26.46199263560306 and parameters: {'alpha': 3.2186679716746727}. Best is trial 45 with value: 26.461989477384442.
[I 2025-09-26 11:48:54,126] Trial 49 finished with value: 26.46199060621546 and parameters: {'alpha': 7.03263534453934}. Best is trial 45 with value: 26.461989477384442.

Level 2 Stacking RMSE: 26.4622
==================================================
ENSEMBLE RESULTS SUMMARY
==================================================
LightGBM RMSE:     26.4635
XGBoost RMSE:      26.4648
CatBoost RMSE:     26.4641
Simple Average:    26.4633
Weighted Average:  26.4633
Ridge          : 26.4629
ElasticNet     : 26.4629
LightGBM_Meta  : 26.4631
Level 2 Stacking:  26.4622

Best Level 1: ElasticNet with RMSE: 26.4629
Level 2 stacking is the best!

Final ensemble RMSE: 26.4622
==================================================
SAVING PREDICTIONS
==================================================
✓ LightGBM submission saved!
✓ XGBoost submission saved!
✓ CatBoost submission saved!
✓ Simple Average submission saved!
✓ Weighted Average submission saved!
✓ ElasticNet Meta-model submission saved!
✓ Final Level2_Stacking submission saved!
✓ All predictions comparison saved!
✓ Results summary saved to ensemble-results-summary.json!

==================================================
SUBMISSION FILES CREATED:
==================================================
Individual Models:
- attempt-lightgbm.csv
- attempt-xgboost.csv
- attempt-catboost.csv

Ensemble Methods:
- attempt-simple-average.csv
- attempt-weighted-average.csv
- attempt-elasticnet-meta.csv
- attempt-ridge-meta.csv (if saved separately)
- attempt-lightgbm_meta-meta.csv (if saved separately)

Final Ensemble:
- attempt-final-level2_stacking.csv

Comparison & Analysis:
- all-predictions-comparison.csv
- ensemble-results-summary.json

🏆 RECOMMENDED SUBMISSION: attempt-final-level2_stacking.csv
📊 Expected performance: 26.4622 RMSE

==================================================
PERFORMANCE COMPARISON:
==================================================
LightGBM:        26.4635
XGBoost:         26.4648
CatBoost:        26.4641
Simple Avg:      ~25.9342 (estimated)
Weighted Avg:    ~25.6696 (estimated)
Ridge          : 26.4629
ElasticNet     : 26.4629
LightGBM_Meta  : 26.4631
Level 2 Stack:   26.4622

==================================================
TRAINING LIGHTGBM WITH OPTIMIZED PARAMS
==================================================
Training fold 1/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[19]	valid_0's l2: 702.293
Training fold 2/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[12]	valid_0's l2: 701.19
Training fold 3/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[18]	valid_0's l2: 697.012
Training fold 4/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[19]	valid_0's l2: 702.178
Training fold 5/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[27]	valid_0's l2: 700.27
Training fold 6/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[13]	valid_0's l2: 699.991
Training fold 7/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[19]	valid_0's l2: 704.618
Training fold 8/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[16]	valid_0's l2: 698.162
Training fold 9/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[28]	valid_0's l2: 699.152
Training fold 10/10 >>>
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[41]	valid_0's l2: 698.921
LightGBM OOF RMSE: 26.4647
==================================================
TRAINING XGBOOST WITH OPTIMIZED PARAMS
==================================================
Training fold 1/10 >>>
Training fold 2/10 >>>
Training fold 3/10 >>>
Training fold 4/10 >>>
Training fold 5/10 >>>
Training fold 6/10 >>>
Training fold 7/10 >>>
Training fold 8/10 >>>
Training fold 9/10 >>>
Training fold 10/10 >>>
XGBoost OOF RMSE: 26.4688
==================================================
TRAINING CATBOOST WITH OPTIMIZED PARAMS
==================================================
Training fold 1/10 >>>
Training fold 2/10 >>>
Training fold 3/10 >>>
Training fold 4/10 >>>
Training fold 5/10 >>>
Training fold 6/10 >>>
Training fold 7/10 >>>
Training fold 8/10 >>>
Training fold 9/10 >>>
Training fold 10/10 >>>
CatBoost OOF RMSE: 26.4650
==================================================
CREATING STACKED ENSEMBLE WITH TUNED META-MODELS
==================================================
Stacking features shape: (471748, 3)
Individual model correlations:
LGBM vs XGB: 0.4780
LGBM vs CB: 0.6973
XGB vs CB: 0.4622

Testing Ridge as meta-model...
Ridge Meta-model RMSE: 26.4634

Testing ElasticNet as meta-model...
ElasticNet Meta-model RMSE: 26.4638

Testing LightGBM_Meta as meta-model...
LightGBM_Meta Meta-model RMSE: 26.4659

==================================================
ADVANCED: MULTI-LEVEL STACKING
==================================================
Level 2 Stacking RMSE: 26.4626
==================================================
ENSEMBLE RESULTS SUMMARY
==================================================
LightGBM RMSE:     26.4647
XGBoost RMSE:      26.4688
CatBoost RMSE:     26.4650
Simple Average:    26.4642
Weighted Average:  26.4642
Ridge          : 26.4634
ElasticNet     : 26.4638
LightGBM_Meta  : 26.4659
Level 2 Stacking:  26.4626

Best Level 1: Ridge with RMSE: 26.4634
Level 2 stacking is the best!

Final ensemble RMSE: 26.4626
==================================================
SAVING PREDICTIONS
==================================================

KeyError: 'sample_id'